### ISSUE TITLE
Allow sorting the Pokémon's ascending or descending

### ISSUE THREAD

**Issue by Shirra2006** [poketwo/poketwo#108]
So....I just noticed right now that when ordering Pokémons based on level, it only shows ascending, not descending. Although you can press back, I still think that it would be nice to have a way to order based on iv in an ascending order and Pokedex, number, level in a descending order. Maybe add the commands: `p!or level -`, `p!or pokedex -`, `p!or number -`, `p!or iv +`

**Comment by mystcuro** [comment]
Its by default in descending order. So if you go backward from first page you will have ascending order. For example: First sort with IV then type p!p and then p!b.

**Comment by person583375239** [comment]
OP is already aware of that method, they just think it would be good to allow it to be sorted either way instead (which I guess I agree with, would be useful)

**Comment by WitherredAway** [comment]
Implemented in `[e7d33fe](https://github.com/poketwo/poketwo/commit/e7d33fe8ef18a06ad2c3ab556e9274ac87626a57)`, thanks for your suggestion!
