### ISSUE TITLE
Daily, Weekly, and Monthly Quests

### ISSUE THREAD

**Issue by Kuraven** [poketwo/poketwo#110]
While reading through other requests related to the stimulation of the economy, I came up with the idea of a quest system that would also help increase pokecoin income for all players. The system would have a daily, weekly, and monthly quest, as seen in the title. Daily quests can have 500-1.5k pokecoins as a prize for catching specific pokemon, doing specific actions with them (trade, SUCCESSFULLY selling or auctioning them in the market or auction house, catching (n) number of said pokemon, catching that pokemon while alsp requiring it to have a certain lvl &/or IV, etc.). For the small prize that daily quests have, I think the quests should be fairly simple, such as "Catch this < common 1st stage pokemon> 5 times today to claim 500 pc!" or "Catch <somewhat uncommon 2nd stage pokemon> twice to receive 750 pc!" and as the rarity of the required pokemon (and difficulty of the action(s)) increases, the prize also increases, maxing out at around 1.5k pc. Weekly quests would have more difficult quests, such as "Win a battle with this/these Pokémon for 2000 pc! (pokemon1), (pokemon2), etc.", "Successfuly win an auction with a bid higher than <some price within the range of 5k-8k> to receive 10k pokecoins!", or "Buy this <rare 3rd stage pokemon or alolan form of a pokemon> for 10k pokecoins!" As the "tier" of the quest (daily, weekly, monthly) increases, the difficulty, rewards, and number of quests required to win the quest prizes increases. I feel like there could also be a feature to win boxes from higher tier quests, ranging from great to master boxes (normal boxes are kind of useless. sry oliver lol). There could also be a p!quests command that shows you the list of quests you must complete. I don't think the system should run on a global timer. what I mean by this is that I don't think we should all get new quests at the same time. I think everyone should be able to do, for example, "p!queststart daily" or "p!queststart weekly" etc. and have a "countdown" until their quest timer runs out and they must start a new one. For things like monthly quests, I feel like there should be some type of compensation for being unable to complete the quest if you have made a lot of progress on it, so that your efforts aren't for nothing. For ex: if you have completed 2 of the 4 tasks required to win the quest prize for that month, then you would get 25% of the quest prizes (½ of your percent of completion), so if the monthly quest prize was 75k and a couple master boxes, then you'd get 18,750 pc, and an ultra/great box. I feel like there's some tinkering to be done with this idea to balance out the prizes in relation to the market and stuff (pokemon could also be given as prizes***), and suggestions are always welcome in the comments (just be nice). When doing "p!queststart <quest type>", I think there should be an embed showing the rewards, but not the requirements. You can also label some of the rewards as "Mystery!" until the person actually starts the quest. I would also recommend a reroll command, "p!questreroll <quest type>." I don't think daily quests should have this feature, since you'll have another quest by the next day, but I think you should have the ability to reroll weekly quests 2 times per month and monthly quests once a month. A confirmation message (like the checkmark reaction thing for entering trades) would be ideal for starting and rerolling quests. 

I feel like boxes don't quite cut it for poketwo, so this would be fun to play, and it'd also give more things for the players to do other than spam random messages/talk to their friends in order to grind poketwo. It gives players something to work for and look forward to, not to mention that unlike boxes, you know what you're going to get and you can decide whether or not it's worth working towards. I don't know how much of this will actually get incorporated, but all I wish for is to have Oliver read this feature request and consider adding the features I listed above.

***If the quest system gets added and pokemon are given as prizes, I feel like everyone would rly appreciate it if the bot gave you an increased chance of receiving the pokemon you shiny hunt as a prize, while also adding to your shiny hunt chain. Thanks for anyone who read this far :D

Edit: I can spell >.>

Edit: Spelling again ;-;

**Comment by unknownking31** [comment]
Ouests are planned

**Comment by Moscimer** [comment]
I think that battling or market/auction related challenges will be too easy to abuse in private servers, but I like the idea.

**Comment by Kuraven** [comment]
> I think that battling or market/auction related challenges will be too easy to abuse in private servers, but I like the idea.

I thought about that too, but that's why I recommended the use of multiple tasks for weekly and monthly quests, so it's not just those extremely easy tasks u can fake in private servers to win. Also, there's already an issue with ppl using alts in ways I won't disclose in order to farm pokemon while afk.

**Comment by Kuraven** [comment]
> Ouests are planned 

I son't think I quite got what you're saying. Sorry.

**Comment by unknownking31** [comment]
> > Ouests are planned
> 
> I don't think I quite got what you're saying. Sorry.

Hmm u can see #29

**Comment by Kuraven** [comment]
> > > Ouests are planned
> > 
> > I don't think I quite got what you're saying. Sorry.
> 
> Hmm u can see issue number  #29 

O ok thanks. Looks really similar to what I said. I didn't read all of the requests tho, just the first one at the top

**Comment by HOPE-NEXUS** [comment]
Hm,nice idea and that will help the people!

**Comment by michaelsong4399** [comment]
Feature added in https://github.com/poketwo/poketwo/commit/f4f31c94ea09b37030b99dc1ce10c05cb9c2ae32.
