### ISSUE TITLE
Freeze Status in battle

### ISSUE THREAD

**Issue by SoloCatching** [poketwo/poketwo#115]
so i just tested status moves on battle. i learned that freeze status inflicted by attack moves are permanent (making the poke inflited by freeze miss all attacks) even if i switch out the poke, it should have a timer or is it hard to put timer on the freeze status?

**Comment by SoloCatching** [comment]
or make the freeze status lifted when you recieve damage

**Comment by michaelsong4399** [comment]
Hello, this is a known bug related to battling. Developers will finish writing the battling system when the bot revamp is complete. We are currently working on reducing bot lag for all users and adding scalability to the bot. Thanks for the suggestion! Hope this helps.
