### ISSUE TITLE
List of freshly caught pokemons

### ISSUE THREAD

**Issue by Roli0109** [poketwo/poketwo#120]
the idea came from the pokemon go finder

For example 

P!age 0

**Comment by oliver-ni** [comment]
More specific please

**Comment by Roli0109** [comment]
@oliver-ni lists the pokemons you have caught in the past 24 hours

**Comment by michaelsong4399** [comment]
Hello, can you please elaborate on how this function's commands would look like and how it will help Poketwo users? That would be greatly appreciated. Thanks.

**Comment by Roli0109** [comment]
Age (in Days): Search "age" plus a number to see how many days ago you caught a particular Pokémon. For example, "age0" will show Pokémon you caught within the last 24 hours and “age1” will show Pokémon you caught 24 to 48 hours ago.
Forexample 
P!age 0

**Comment by WitherredAway** [comment]
This is partially possible right now by:
`p!order number` -> `p!p` -> `p!last` which will show you all the recently caught pokemon
Although not sortable by time and such, i personally think that is enough

**Comment by WitherredAway** [comment]
With the new feature implemented in e7d33fe8ef18a06ad2c3ab556e9274ac87626a57, this is now possible to do using `p!order number-` (will order your pokemon by the ID, effectively sorting by the order in which they were caught) and then using `p!pokemon` to view the pokemon.
