### ISSUE TITLE
Hints are sometimes blank

### ISSUE THREAD

**Issue by person583375239** [poketwo/poketwo#122]
**Describe the bug**
Hints sometimes give zero letters

**To Reproduce**
Repeatedly try to get hints. It happened for me on Tapu Lele

**Expected behavior**
The hint should give a minimum number of letters (perhaps as a % of the total number of characters in the name)

**Screenshots**
![image](https://user-images.githubusercontent.com/39986236/105016881-18c3fd80-5a3b-11eb-8a8f-d7c95e269079.png)

**Additional context**
n/a

**Comment by oliver-ni** [comment]
This is intended behavior. However, the hint system does need a revamp so I'll keep this issue open.
