### ISSUE TITLE
Redirecting level up embeds to one channel.

### ISSUE THREAD

**Issue by oofsauce** [poketwo/poketwo#134]
**Is your feature request related to a problem? Please describe.**
Users find the level up embeds annoying, but still want to know when it happens.

**Describe the solution you'd like**
A setting that allows you to redirect all level up notifications to one specific channel (that optionally pings the user).

**Comment by unknownking31** [comment]
This functionality wont be added probably. 
 https://github.com/oliver-ni/poketwo/issues/13#issuecomment-726494170
