### ISSUE TITLE
New type of battle

### ISSUE THREAD

**Issue by Brugify** [poketwo/poketwo#135]
I want I new kind of battle in the game because after doing the same battle over and over it starts to get less fun

I think a battling system with more than just 3 pokemon (like 6) would be interesting to play with

**Comment by michaelsong4399** [comment]
Hello, battling will be completely recoded once Oliver rewrites the bot! A lot of community suggestions about battling will also be considered then. Feel free to bring this issue back up in the future. Thanks for your suggestion!
