### ISSUE TITLE
Boxes can be opened twice - race condition issue?

### ISSUE THREAD

**Issue by person583375239** [poketwo/poketwo#143]
**Describe the bug**
1 box can be opened twice if attempted to be opened in quick succession. (Obligatory: _I am not a dev_), but it seems like a race condition bug. I am not actually certain whether the box reward is counted twice, but I would assume so considering that I was left with -1 boxes (see screenshot). I wasn't certain of my _before_ balance so it's hard to say.

**To Reproduce**
1 - Have 1 box available to open
2 - Artifically cause discord grey text by spamming messages
3 - While the messages are catching up, send 2 commands to open a box
4 - See that the box is visibly opened twice
5 - See that you are left with -1 boxes

**Expected behavior**
For there to be no way to open 1 box twice

**Screenshots**
![image](https://user-images.githubusercontent.com/39986236/107142261-7c986280-6925-11eb-83ca-0eb82417a3d4.png)

**Additional context**
Would it be possible to fix whatever state my box number is in please? Especially because it was a master box, I don't want any future ones to stop working ;_;

**Comment by NathNathNathNath** [comment]
(I should probably add that this was unintentional - I ran the command twice because I thought the initial one didn't register)

**Comment by bruh1010101010** [comment]
i have like -40 to -50 lol op glitch

**Comment by oliver-ni** [comment]
This exists right now, but it's not too important to me as in the long run you can't get more or lose out on boxes.

If it's at -1, that means you opened two when you only had one, and the next time you vote it'll go back up to 0 so it balances out. You basically just got it early

**Comment by cillosis** [comment]
> This exists right now, but it's not too important to me as in the long run you can't get more or lose out on boxes.
> 
> If it's at -1, that means you opened two when you only had one, and the next time you vote it'll go back up to 0 so it balances out. You basically just got it early


> This exists right now, but it's not too important to me as in the long run you can't get more or lose out on boxes.
> 
> If it's at -1, that means you opened two when you only had one, and the next time you vote it'll go back up to 0 so it balances out. You basically just got it early

So you guys are shorting the  box stock like $GME. This won't take you to the moon so prob not a good WSB.

**Comment by oliver-ni** [comment]
Fixed by #180
