### ISSUE TITLE
Allow Pokemon to learn Egg Moves

### ISSUE THREAD

**Issue by ManfranMike** [poketwo/poketwo#146]
**Is your feature request related to a problem? Please describe.**
My favorite Pokemon is Froslass. I like using Froslass as a "suicide lead" in competitive battles with the official games or with Pokemon Showdown. A staple move in the moveset for a Froslass in that role is Spikes. Spikes can only be learned by Froslass through a series of breeding other pokemon.

Breeding and Egg Moves are not implemented in the current version of PokeTwo, so there is no way to get a Froslass that knows the move Spikes.

**Describe the solution you'd like**
The easiest way to solve this issue is by adding all Egg Moves a Pokemon can have to their list of available moves.

**Additional context**
A Froslass using Spikes is used as the picture on the Bulbapedia article for Spikes: https://bulbapedia.bulbagarden.net/wiki/Spikes_(move)

**Comment by WitherredAway** [comment]
This is planned on the [roadmap](https://github.com/poketwo/poketwo#roadmap)
