### ISSUE TITLE
A better FAQs system with the staff about upcoming changes

### ISSUE THREAD

**Issue by richardwuisawesome** [poketwo/poketwo#151]
I have a lot of questions regarding forms and form changes, and status moves and held items, what is the best way to contact and understand exactly what direction we're going with that? I know zygarde will be able to change forms from 10% to complete, but I'm not sure about pokemon such as meloetta and deoxys. Will form changes be moves in battle, shop items, or only catchable, separate pokemon like they are now?

Thanks!

**Comment by oliver-ni** [comment]
I'm not too sure myself, but we'll release more information about it as I figure things out.

They won't be battle-exclusive, they'll most likely be some item / command.
