### ISSUE TITLE
Some moves don't exist

### ISSUE THREAD

**Issue by Qwertyaloo16** [poketwo/poketwo#154]
There are some moves that if u search for there is a description but no Pokemon can learn that move. For example Dragon Ascent it can be learned by mega requaza usually but when I do p!moves it does not show up . but if search the move it comes up with the correct power and pp

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by unknownking31** [comment]
Tbh thats not a bug its just because dragon ascent can only be learned via move tutor until gen 8(its level 1move in gen 8),same for many other signature moves

**Comment by unknownking31** [comment]
Moveset will be updated with new gen's addition

**Comment by WitherredAway** [comment]
Update of moveset to match gen 8 is planned, no ETA however.
