### ISSUE TITLE
Add logins for the bot

### ISSUE THREAD

**Issue by Jay7Discord** [poketwo/poketwo#163]
**Is your feature request related to a problem? Please describe.**
So lets say you get blocked out of your account, terminated, or just forget the password to your discord in general, you would loose all your progress, no matter if you have been playing for ages and broke no discord rule, even if you spent money.

**Describe the solution you'd like**
There should be logins, that the bot gives you once you run your first command, it will contain a password and username, both randomly generated and extremely hard to get into *to prevent cracking or account stealing* and also a warning that would tell you not to give your login to nobody no matter what, and if you do, then its your fault. You save that login, and if you get logged out of your discord you can get into another account and login with that code p!login --username --password. It will give you everything that you lost. Also only 1 acc can be on a login at a time, and in the case of anyone selling their logins, their login gets automatically deleted from the database, to prevent selling logins.
**Additional context**
This is used in lots of vouch bots, and it makes everything better, especially since you dont loose everything, now i understand that with so much people using the bot it would be hard, thats why maybe it would just be better to have p!recover and a staff could help you recovering your profile which is stored in a database with a random tag that only you and the staff have access too. ok ty

**Comment by 00-00-00-11** [comment]
will open account share and trading of illegal alts.

**Comment by yorii260** [comment]
I found it interesting, it happened to me a little while ago that I lost my main account

**Comment by silasary** [comment]
This opens up a huge can of worms regarding selling/stealing accounts and I don't see too much of a benefit.

People should take more care of their Discord login.

(Counterpoint, due to the 100 server limit, I have an alt account.  I would like to share my poketwo progress between them, and be logged into both at once)
