### ISSUE TITLE
Battling

### ISSUE THREAD

**Issue by Zeroaster-da** [poketwo/poketwo#168]
I always think of why we can only add 3 Pokémons in a battle . I think you should add a feature in which like we can minimum add 3 Pokémons and 6 Pokémons maximum .
Why?. This will make a perfect battle while battling with someone!

**Comment by Kuraven** [comment]
This is already in the list of planned updates. Thousands of people already want this. Just close the feature request/issue

**Comment by adacker10** [comment]
Keemroh sold me an autocatcher
