### ISSUE TITLE
Computer Battle

### ISSUE THREAD

**Issue by Zeroaster-da** [poketwo/poketwo#170]
COMPUTER BATTLE =

Okay if you add the feature “Computer Battle” it will be a good training for users to battle with their friends other. 

   What features should be in Computer battle?

In computer battle you should something like we can choose the opponents Pokémons and battle them to know which moves will work , weakness,etc.

So , i think it will be great!

**Comment by Nutty-hy** [comment]
That looks like a great idea to me .
It will be helpful for training nice!

**Comment by Kuraven** [comment]
yeah this isn't really worth the time or resources. You can easily figure all of this stuff out by spending 2 minutes in google. Not worth it and i'm not really seeing anything interesting or new here lol

**Comment by Nutty-hy** [comment]
Computer battle looks better to me than searching google . 🤔

**Comment by Zeroaster-da** [comment]
Making computer battle isn’t easy actually .
Just a idea.

**Comment by Kuraven** [comment]
> computer battle looks better to me than searching google 
sorry u're too lazy to literally just google one thing lmfao

>Making computer battle isn’t easy actually. Just a idea.
never said it was

**Comment by oliver-ni** [comment]
This is outside the scope of the bot at the time.
