### ISSUE TITLE
install

### ISSUE THREAD

**Issue by GalackQSM** [poketwo/poketwo#171]
a tutorial to install it?

**Comment by NathNathNathNath** [comment]
1. Be an admin on the discord server
2. Go here: https://invite.poketwo.net/
3. Connect the bot to your server
4. Any further questions can be asked in the #questions-help / #questions-help-2 channels of the official server

**Comment by GalackQSM** [comment]
yes my me I want the bot source to make it my own bot

**Comment by NathNathNathNath** [comment]
I wouldn't know how to answer that, although I can say it is likely way more complicated that you likely think. Regardless, this isn't really what the "issues" on github are for, so could you close this?

thanks

**Comment by kyle-he** [comment]
No

**Comment by Kuraven** [comment]
1) You can't "install" the bot. The code is Oliver's and it's up to him to allow u to use it separately from Poketwo
2) U obv think that bots are easy to make and manage, so let me tell you what would happen if you somehow did get your hands on the entire bot code;
you'd get a running bot but none of your player data would be there.

3) there's a channel called #questions-help in the OS. This isn't a feature request or a bug report, so don't make pointless stuff like this.
