### ISSUE TITLE
Hello #trading-talk, i see you are all talking about auto market snipers!

### ISSUE THREAD

**Issue by Drxxy77** [poketwo/poketwo#175]
(KeemROH here)

I wanted to say yes, ive made them before, and yes, they work amazingly :)

**Comment by Drxxy77** [comment]
i also want to add that u can get an autocatcher for cheap at
dsc.gg/autocatcher
also
<@611659645760831506> please consider my deal :p

**Comment by Drxxy77** [comment]
ngl im mad horny rn

**Comment by Drxxy77** [comment]
never gonna give you up

**Comment by Drxxy77** [comment]
never gonna let you down

**Comment by Drxxy77** [comment]
never gonna turn around

**Comment by Drxxy77** [comment]
and desert you

**Comment by Drxxy77** [comment]
stop

**Comment by Drxxy77** [comment]
deleting

**Comment by Drxxy77** [comment]
me

**Comment by Drxxy77** [comment]
reeeeeee

**Comment by kyle-he** [comment]
No

**Comment by Hyperclaw79** [comment]
lmao the most desperately lying scammer
