### ISSUE TITLE
**CRITICAL ISSUE** Pokémon Duplication

### ISSUE THREAD

**Issue by HitlistCFGS** [poketwo/poketwo#177]
This is KeemROH (Add me back bub)
I've discovered a bud that allows me to duplicate any pokemon in my inventory, I'm willing to have a one on one with you and showing you the bug in action (I WILL NOT BE RELEASING THIS BUG TO ANYONE BUT THE ADMINS, thank you )

**Comment by HitlistCFGS** [comment]
bump

**Comment by HitlistCFGS** [comment]
im so fucking serious im trying to show u guys the bug one on one

**Comment by HitlistCFGS** [comment]
! ! KeemROH#9436

**Comment by yorii260** [comment]
bruh

**Comment by Kuraven** [comment]
why don't u just DM oliver or an admin if the issue is that dire

i don't even think that any of the admins with the exception of oliver check these github issues/feature requests

**Comment by oliver-ni** [comment]
Feel free to DM me instead of trying to attention grab here.
