### ISSUE TITLE
Feel free to DM me instead of trying to attention grab here.

### ISSUE THREAD

**Issue by HitlistCFGS** [poketwo/poketwo#178]
Feel free to DM me instead of trying to attention grab here.

_Originally posted by @oliver-ni in https://github.com/poketwo/poketwo/issues/177#issuecomment-803226805_

Cant dm you if im banned from the official server and literally every possible mutual server we could possibly have that I am aware of...

**Comment by oliver-ni** [comment]
Your main account is also banned from our GitHub, and for good reason.

Feel free to contact me via email then. It's on our website footer.
