### ISSUE TITLE
Suggestions for stopping/reducing market snipers/scalpers/auto-buying bots

### ISSUE THREAD

**Issue by person583375239** [poketwo/poketwo#179]
**Is your feature request related to a problem? Please describe.**
The problem is market snipers/scalpers/auto-buying bots

**Describe the solution you'd like**
1 - I wanted to suggest that there be an extra long delay (minutes, not seconds) between market searches using certain flags (sh/al/leg/my/ub/ev)

2 - Or, perhaps implement a limit on the amount of searches that can be done using these flags in a 24 hour window

3 - A combination of both of the above might work

**Comment by kyle-he** [comment]
The cooldown is long enough already - something that may be a bit better would be to calculate the amount of *time* you spend searching market (ie 30 hours straight of market searches)

**Comment by person583375239** [comment]
That's a good idea

I don't necessarily agree that the cooldown is long enough already (for these specific kinds of searches, example: p!m s --sh --o id- --lim 3) thought.

Every 5 seconds is still quick enough that it won't dissuade most people, automated or not. imo anyway

**Comment by infinitiive** [comment]
I’m a bit confused about why “snipers/scalpers” are a problem. Obviously auto-buying bots are unfair and banned by the ToS, but for people doing market sniping/scalping legitimately (ie searching market and buying by hand), I’m confused about why this is an issue. If everybody has the same opportunity to use the market this way, I don’t see why limiting commands/enforcing a cooldown is necessary or helpful.

**Comment by person583375239** [comment]
Yeah I agree about the main concern being the auto-buy bots.

Putting some kind of limit on the few people who are able to spam market searches all day gives more opportunity to the other 99% of players, who don't have the time to do that.

btw, I'm not biased in saying this, if I wanted to put in the effort I could be one of those people myself, I do have the time etc

**Comment by cillosis** [comment]
As someone who has probed (manually) looking for opportunities, I think your sugggestion lacks merit. Essentially you are mad others get deals before you? That is not a code problem and does not belong here. Will close unless you have a constructive solution.

**Comment by person583375239** [comment]
Hi @cillosis

As I mentioned above I am not actually suggesting this for my _own_ benefit - I have always preferred just catching pokemon and selling them to make pc. I don't think sniping is worth the effort for me personally.

> Essentially you are mad others get deals before you?
 No. This is an assumption and unnecessarily hostile.

> not a code problem and does not belong here.
I agree it's not a code problem, which is why I labelled it as an enhancement and not an issue.

> Will close unless you have a constructive solution.
I don't have any other ideas other than the ones mentioned
