### ISSUE TITLE
Allow non-admins to use incense

### ISSUE THREAD

**Issue by tehstone** [poketwo/poketwo#182]
Problem:
A user buys an incense and then is unable to use it. Current workarounds include: giving that user temp admin perms (very bad), having the user instead send a server admin 10k coins so they can purchase an incense (also pretty bad).

Possible Solutions in order of preference:
- Tie incense use to a configurable role per server. Any user with that role can start an incense but has no additional abilities. This way an admin can grant that role temporarily or to trusted users.
- Limit incense to channels already having spawns enabled via `p!redirect` or alternately have a separate setting for incense channels with an additional command to set incense channels.
- Allow incense use to be toggled at the server level between admin only and all users.
- Allow incense to be gifted. Users can then buy incense and send it to the admin to be used.
- Allow shards to be converted to pokecoins. Users can then buy shards, convert to coins and then send coins to an admin.

Most of the possible solutions listed above still have downsides but all are better than the current situation. Currently if a user buys shards with the intent to purchase incense before realizing they can't use that incense they are stuck with it and there is no way to resolve except to create a personal server and use the incense there.

**Comment by Kuraven** [comment]
Not a bad idea, but idk if they'll go through all of that effort just to allow random players in OS to start a few incenses. I agree with the whole shards thing, though. I don't understand why they exist or why we have to turn pc into shards when we could just as easily buy stuff with pc.

**Comment by kyle-he** [comment]
I personally think that allowing incenses to be started by anyone is fine as long as admins have the ability to stop it. I don't think there will be many issues with people "raiding" servers using incense—people only have so many pokecoins—and incenses aren't much different from redeeming or using bot commands in the wrong channels.

**Comment by oliver-ni** [comment]
That is a good point. I'll think it over. If anyone has thoughts to contribute, please feel free to as well :)

**Comment by LazyGamer397** [comment]
What if there were a couple channels specifically for incense with spawns NOT a redirected there? That way, normal bot spawns won't override the incense spawns and I agree with the incense starting role. Also, if someone wanted to start an incense, they can simply message a staff member maybe to request the role and incense channels can also be locked while incense is NOT active. As for the role, once the incense has been purchased, role should be immediately removed.

**Comment by JustTom7** [comment]
In my server, we have designated channels for incense in which spawns are not directed. This is intentional so that spawns are not overwrited. I wouldn't want spawns to be started anywhere else other than these designated incense channels.

I like the idea of anyone being able to start incense, but only within designated channels, and with permission (in the form of a temporary incense role, that does not require admin perms). 

The difference between using other bot commands and incense in an incorrect channel is that usually if bot commands are used in chat, a user will be asked to stop by another member, they will generally listen and move to the correct channel. An incense will go on for an hour, and a regular member has no way of stopping it other than pinging an admin and hoping someone is around.

**Comment by Haltfire30** [comment]
I think a config for each channel could be a potential solution. The bot joins a server at a default of admins-only incense, but an admin could type, for example, "p!config incense all", allowing all users to use incense in that specific channel.

**Comment by RedVertigoFox** [comment]
I think that they don't so servers don't get spammy. and if people have designated channels they wouldn't want someone to use an incense in general or something

**Comment by michaelsong4399** [comment]
I thought about adding incense role permissions to guild configs where guild admins can change, but that might be complicated for players to understand. In my opinion the support for an `incense` role could be sufficient.

**Comment by ihemantkumar** [comment]
> I think the best way forward is to allow anyone to start incenses in channels that have spawns enabled via redirect, as well as an incense role that can start them in any channel.
> 
> Natural spawns would then be disabled in channels with incense active.

Will there be any issues with users using incense on their own? Like processing issues and load on the bot, crashes etc?

**Comment by msmagoo87** [comment]
This seems to have gone stale. Would be cool to see a decision on this so someone could contribute the solution!

**Comment by WitherredAway** [comment]
This has been implemented! To allow anyone to start incenses in a server without giving them admin, just give them a role named "Incense"
