### ISSUE TITLE
Something about lowballers

### ISSUE THREAD

**Issue by RedVertigoFox** [poketwo/poketwo#187]
We have gotten so much more people who lowball are the worst especially for people in small servers where they can't ask (also maybe a language barrier), it should be a proper ban from p2 AND if reported the player auto gets their stuff back that was lowballed, especially  people flex their lowballs infront of them and we can't do anything about it

**Comment by oliver-ni** [comment]
We can't feasibly moderate every instance of lowballing that happens throughout the bot, _nor should we_. When a trade between two parties happens, it is fair, as both parties have agreed to the terms. While there may be some unfriendly users who rip off others, ultimately it is the player's responsibility to evaluate whether it is a good deal or not.

It's not possible to even concretely define what a lowball is, much rather set rules on them. Value is subjective. Items are worth different amounts to different people. Even going off the intentions of each party, intentions are often mixed and unclear, and I don't believe it's wrong for people to want to get a good deal.

Say you want to buy an item—you'd obviously want to buy it for the cheapest price possible. You'd maybe even hop between different sellers, making them compete to offer you the best price. If someone came to you with an amazing price, much less than the market value, would you accept it? Obviously you'd want to, but under a lowballing policy, buyers would be stressed and scared of accidentally "lowballing". Where do you draw the line between haggling and lowballing?

Enforcing lowballs/highballs would be inconsistent at best and damaging at worst—in addition to people getting mad about getting punished for lowballing which they might not agree with, we also in a way say it's ok for people to change their minds about something after the deal is finished.

While we've never had a bot-wide rule on lowballing, we've had a similar policy in the official server in the past and observed all the effects I just described and more. It also caused quite a lot of conflict in the community, and overworked our staff members. In December, we stopped moderating trades there. This is part of the reason why we now have an extensive [trading tips document](https://docs.google.com/document/d/1RJIGeUXqYyZXB7hBacsLb4FR7CQj42AbQS-FhBVNyN0/edit) and post a reminder minute regarding it every minute in the trading channels. I believe that the chance in policy has led to much more consistent punishments, and an overall healthier community.

Keep in mind that while we don't punish individual instances of lowballing, repeatedly causing large disruptions in the bot's community, trading-related or not, can get your account banned.
