### ISSUE TITLE
Bots that tells the name of Pokémon spawns...

### ISSUE THREAD

**Issue by TrashUwU** [poketwo/poketwo#193]
Why did I get blacklisted for using [this](https://github.com/TrashUwU/PokeAssistant)? It's not against Discord TOS?

**Comment by bobbers0n** [comment]
It’s clearly against Pokétwo TOS. The repository literally has tags called poketwo-cheats/hacks ❗️❗️And why do you act like you’re adding new features to that copied bot when it’s just changing the readme? Them commits💀

**Comment by TrashUwU** [comment]
> It’s clearly against Pokétwo TOS. The repository literally has tags called poketwo-cheats/hacks ❗️❗️And why do you act like you’re adding new features to that copied bot when it’s just changing the readme? Them commits💀

Because it evals a code from my website. I need to blank commit to show something has `Changed`. Can't just announce new features without committing. And why do you think it's against Poketwo TOS? Moderators say it is not.

**Comment by person583375239** [comment]
> It’s clearly against Pokétwo TOS

This is false. It **might** be, but it definitely isn't clear whether this breaks the rules or not. The rules need to be updated imo, if using this does equal a ban

**Comment by TrashUwU** [comment]
> > It’s clearly against Pokétwo TOS
> 
> This is false. It **might** be, but it definitely isn't clear whether this breaks the rules or not. The rules need to be updated imo, if using this does equal a ban. I think a ban/blacklist is too harsh for this anyway, personally

I don't think it's against TOS. Poketwo is not Pokecord. Poketwo says the name of the pokemon that despawns and also has the Who-is-That-Pokemon channel in the support server. I guess the moderators thought it's against TOS, most of them do not read the whole thing and start assuming it's an `auto-catcher`.

**Comment by bobbers0n** [comment]
> This is false. It **might** be, but it definitely isn't clear whether this breaks the rules or not. 

What could this be then? It is automation that grants an advantage over other plays by pinging for legendaries/shiny hunts.
![Rule1](https://user-images.githubusercontent.com/81731750/116556805-de84ba80-a8cb-11eb-94ac-7c6d7a40331e.jpeg)

**Comment by TrashUwU** [comment]
> > This is false. It **might** be, but it definitely isn't clear whether this breaks the rules or not.
> 
> What could this be then? It is automation that grants an advantage over other plays by pinging for legendaries/shiny hunts.
> ![Rule1](https://user-images.githubusercontent.com/81731750/116556805-de84ba80-a8cb-11eb-94ac-7c6d7a40331e.jpeg)

It is automation that grants an advantage over other plays by pinging for legendaries/shiny hunts. PokeAssistant is not an automated user account.

**Comment by person583375239** [comment]
> > This is false. It **might** be, but it definitely isn't clear whether this breaks the rules or not.
> 
> What could this be then? It is automation that grants an advantage over other plays by pinging for legendaries/shiny hunts.
> ![Rule1](https://user-images.githubusercontent.com/81731750/116556805-de84ba80-a8cb-11eb-94ac-7c6d7a40331e.jpeg)

Yeah, your screenshot shows that it says "Automating _**user**_ accounts", which TrashUWU's bot **does not do**. Which is why it said it was unclear earlier on.

"It is automation that grants an advantage over other plays by pinging for legendaries/shiny hunts."
Correct, but this kind of thing is not mentioned specifically in the rules

**Comment by TrashUwU** [comment]
Join the Poketwo Server and read this
https://discord.com/channels/716390832034414685/718008298837770290/835574304040026173

**Comment by Amber-Ozen-and-Ibarakazen** [comment]
From what I understand of it, it's just a bot that helps you with the names of pokemon. I might remove the *ping roles for legs* feature but keep the *ping for sh* feature. I can see someone like myself using this for incenses as I have a hard time remembering names and often end up missing most of them.

**Comment by TrashUwU** [comment]
> From what I understand of it, it's just a bot that helps you with the names of pokemon. I might remove the _ping roles for legs_ feature but keep the _ping for sh_ feature. I can see someone like myself using this for incenses as I have a hard time remembering names and often end up missing most of them.

The problem is others can make a bot that searches legendary pokemons in the result. Do you still want me to remove it?

**Comment by Cangey-Profile** [comment]
Its not autocatching because it just tells you the name of the Pokemon using AI. Its not automated catching, so imo its technically not against poketwo's rules.

**Comment by Cangey-Profile** [comment]
It is NOT a user account anyway. It is a bot account, and therefore unable to play Poketwo.

**Comment by oliver-ni** [comment]
We are looking into it. Regardless, this is not the right place to complain about this.
