### ISSUE TITLE
STAB 

### ISSUE THREAD

**Issue by YuraJE4K** [poketwo/poketwo#198]
I suggest to add stab, it exist in all pokemon games/bot
**What is Stab**
Its increasing damage in Duels.In the Damage, if the move type is same as any of the pokemon's type, damage is increased by 150% (multiplied by 1.5).
For example if Pikachu uses Electric type moves, the Damage is 1.5x more then the normal damage.

**Comment by YuraJE4K** [comment]
Can I ask where exactly is damage calculated? I cant find

**Comment by Wiper-R** [comment]
> Can I ask where exactly is damage calculated? I cant find

data ~ models ~ Move ~ calculate turn

**Comment by oliver-ni** [comment]
This will be added in the next update.
