### ISSUE TITLE
Daycare

### ISSUE THREAD

**Issue by Pro720** [poketwo/poketwo#200]
There is always a problem of daycare like if we don't have time or we don't wanna level up pokes on own so daycares comes to mind but there is a risk of scamming

As a solutions you should add a rent feature in which people can rent their Pokemons for a certain period of time and after that period of time they can take it back so no scamming risk . It is going to also help in improving economy .

**Comment by Pro720** [comment]
@person583375239 if we give the bot to daycare the Pokemon so the Pokecoins are going but its not going to the players so in short if we give to the players then it is going to benefit the economy

**Comment by oliver-ni** [comment]
This is outside the scope of the bot, for now. Even if we did want to implement it, there are many complications.
