### ISSUE TITLE
Searching own pokemon takes a very long time

### ISSUE THREAD

**Issue by ghost** [poketwo/poketwo#201]
**Describe the bug**
Running "complicated" searches on your own pokemon takes a very long time, when you have a lot of them. Usually 4 or 5 minutes.

**To Reproduce**
Own many (50k+?) pokemon and run a command like this:
p!p  --spdiv 31 --atkiv >26 --defiv >23 --hpiv >20 --spdefiv >20

**Expected behavior**
The Poketwo bot responds faster.

**Screenshots**
![image](https://user-images.githubusercontent.com/39986236/117691156-809d8000-b1b3-11eb-879f-4a337998db7e.png)

**Additional context**
(Note the timestamp deltas in the screenshot)

**Comment by tirthyme** [comment]
Can you link the section of code that does searches for the Pokemons?

**Comment by rf20008** [comment]
to solve it you could check all the comparisons at the same time

**Comment by WitherredAway** [comment]
Does this need to be pinned still?
