### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Vonomlo** [poketwo/poketwo#205]
hello admins i have a few questions do u get any rewards for compeleting the dex?
and what language does poketwo use?
have a good day!

**Comment by WitherredAway** [comment]
Please ask these questions in #questions-help in the official server.
You don't get any specific reward for completing the dex, but you get 809*35=28315 pokécoins for catching every pokemon once, and more so every 10, 100, 1000, etc catches of each pokémon. The bot uses English. Have a good day too!

**Comment by Vonomlo** [comment]
oh what i meant by language is programming language

**Comment by WitherredAway** [comment]
According to the **Languages** section at the end of the main page (https://github.com/poketwo/poketwo) the bot uses 99.9% Python and 0.1% Dockerfile (no clue what Dockerfile is)

**Comment by Vonomlo** [comment]
idk what dockerfile is too python i am familliar with since i used to program it

**Comment by Vonomlo** [comment]
Since i got the answers i will close this issue
