### ISSUE TITLE
Language of the Pokemon names

### ISSUE THREAD

**Issue by Ps3ydon** [poketwo/poketwo#210]
In different countries and languages the pokemon have different names.
It would be nice if you could implement an option to change the used names on a server.
You don't have to change all masseges of the but, but only the names of the pokemon.
I am german and i have grown up with the german names and for that it's not that easy to guess the names of the pokemon.

It would be really nice if this was possible.

**Comment by WitherredAway** [comment]
Could you explain what you mean a little more? Correct me if I'm wrong but If I understand you correctly you can already use German names to catch pokemon. Do **p!d <pokemon name>** and you can use the name next to any of the flags as alternatives. For example, for Ralts you can use **p!c trasla** to catch it, where 'trasla' is the German name (mentioned next to the German flag in p!d ralts)

**Comment by Ps3ydon** [comment]
Ok, I just tested it and you're right.
I thougt it doesn't works because the names on the pictures of the pokemons are in english.
Sorry for disturbing.
