### ISSUE TITLE
Make auction server independent

### ISSUE THREAD

**Issue by ihemantkumar** [poketwo/poketwo#212]
Issue:
Auction is currently server dependent. Means auction started on my server won't be available on other servers. Players won't be able to sell their pokemon globally.

Solution:
Instead of going to official server, allow all servers to join a common auction. It will allow admins to hold global auction on their servers and players to selle their worthy pokemon for pc. Yes, marketplace is already available but there is no telling when the pokemon is going to sell. 

Plus it's good for other servers. We can host bot but having not able to use global auction makes me wonder if we are not able to use the bot to its best potential.

Please consider.

Well I have another request as well.

Allow to remove pokemon from market or auction. If pokemon doesn't sale for set price, it will give option to player to reset price for better chance of selling.

**Comment by Hyperbub** [comment]
#1 Making Auctions Global
Unfortunately to keep market and auction balanced, their current states will be kept. The main advantage of market is that your target audience is global while auctions are limited to the main server. Auctions can, on the other hand, go for significantly more than one may have expected. To keep this balance and to make sure market actually stays relevant, maintaining these target audiences are important.
#2 Removing Pokemon from Market or Auction
You already can remove pokemon from market. P!remove (id)
Unfortunately to avoid abuse of timings and such, removing auctions will not be an option.

**Comment by Kuraven** [comment]
Also, this has already been a feature request numerous times; read the other feature requests if you're going to make feature requests on the 2 most popular feature requests in the community. Both this and your feature request on the Pokedex registry system were rewrites of an already-existig feature request >.>
