### ISSUE TITLE
Questions about Gen 8 for Poketwo

### ISSUE THREAD

**Issue by Jynx69** [poketwo/poketwo#214]
1.Hi I was wondering will we be getting galarian forms?
2.Will Dynamax be a thing?
3.will get Galarian Articuno,Zapdos,and Moltres?
4.Will Zarude be a thing?
5.Will max raids be a thing?
6.Will the rusted sword and rusted shield be a item?
7.Will gen 8 starters be selectable when starting?
8.Will Breeding be possible
Thank you hope theses questions will be answered

**Comment by FUCKINGNlGGERS** [comment]
Hottest tranny 
[
![image](https://user-images.githubusercontent.com/85089890/120134023-1c525880-c182-11eb-9048-6d1b94442d1b.png)
](url)

**Comment by Madjosz** [comment]
To answer some of your questions:
1. Yes, they are already ingame with a similar spawn rarity to the alolans, e.g. `p!dex galrian zigzagoon`. They don't have other "galarian ..." names than Englisch but you can catch them with their normal name in all available languages.
3. Yes, they are ingame and catchable with spawnweight 2 (UBs have 3, normal legis have 6), check e.g. `p!dex galarian moltres`.
4. Yes, ingame and catchable with normal mythical spawnweigth 12.
7. Yes, check `p!start`.

**Comment by Jynx69** [comment]
Thank you so much for the answers I hope breeding will be possible and dynamax layer on
