### ISSUE TITLE
Battle Not working

### ISSUE THREAD

**Issue by me-coder-1204** [poketwo/poketwo#215]
After we choose our moves in a battle, the bot doesn't respond back. But when I type p!battle, it says I am still in a battle. I experienced this issue today.

How I got it:
-Ask someone for a battle
-Choose your pokemons
-Choose the move in the DM
-That's It

It should have responded in a few seconds and both of us choose our moves. SO the battle should have comtinued.

![image](https://user-images.githubusercontent.com/69784401/120183643-95f35080-c22d-11eb-8926-92863cbdaca5.png)

Nothing Else

Regards

mecoder-1204

**Comment by WitherredAway** [comment]
Is this issue still relevant?

**Comment by WitherredAway** [comment]
I doubt this problem persists still after so long, so i will be closing this issue. Please feel free to reopen if necessary.
