### ISSUE TITLE
every time i try to select my pokemon it won't let me

### ISSUE THREAD

**Issue by tyler545** [poketwo/poketwo#216]
![Screenshot_20210531-224434_Discord](https://user-images.githubusercontent.com/46614002/120272776-71659b80-c262-11eb-8690-4e7f0a740168.jpg)
every time i try it makes me select my most recent catch instead of my 0th pokemon

**Comment by WitherredAway** [comment]
There are two solutions to this bug:
1) Do p!reindex, that should reindex the ID 0 to 1.
2) Do p!s 00 to select the Pokemon at ID 0

**Comment by tyler545** [comment]
thanks, this helped me select it
