### ISSUE TITLE
need help with market command

### ISSUE THREAD

**Issue by tyler545** [poketwo/poketwo#217]
every time i try it won't let me see the pokemon I've listed on the market, and it won't let me search on the market by pokemon name

**Comment by WitherredAway** [comment]
Market Basics:
adding to market: p!m a (id) (price)
searching for pokemon: p!m s --n <pokemon name>
searching for a certain type: p!m s --t <type>
finding your pokemon on the market: p!m s --mi 
removing pokemon: p!m r <id number>

searching for:
legendaries: p!m s --leg
mythicals: p!m s --my
ultra beasts: p!m s --ub
megas: p!m s --mega
alolan: p!m s --al
shinies: p!m s --sh 
Limiting amount shown: --lim <amount>

Only one order command can be used at once
ordering price: --or price+ / - 
--> + will order from least to most expensive, - orders from most to least expensive

ordering id: --or id+ / -
--> + will order from oldest to newest listings, - orders from newest to oldest listings

ordering level: --or level+ / -
--> + will order from lowest to highest level, - orders from lowest to highest level
If trying to find a certain level put --level >/< (insert number) or --level (insert number)

ordering iv: --or iv- / + 
--> + will order from lowest to highest iv, - orders from highest to lowest iv
If trying to find a certain iv put --iv >/< (insert number) 
--> note this can also be used for hpiv atkiv defiv spatkiv spdefiv and spdiv (HP, attack, defense, special attack, special defense, and speed ivs respectively) and multiple iv searches can be used at once.

Ex. p!m s --n pikachu --o price+ --atkiv >27 --spdiv 31 --level >10 --lim 3 3 results for a Pikachu with attack iv above 27, speed iv of 31, level above 10, from least to most expensive

Finding info: p!m i <id number>
Buying a pokemon: p!m b <id number> 
--> The id number will be displayed to the left of the pokemon on the market listing

pokemon bought on the market can not be returned 
if there are any questions about pricing your pokemon for market please go to #price-check

**Comment by WitherredAway** [comment]
-Tag made by yiqii

**Comment by WitherredAway** [comment]
if you need help with anything else please join the official server discord.gg/poketwo or DM me Witherr🖤#5417
