### ISSUE TITLE
Want to contribute to poketwo

### ISSUE THREAD

**Issue by IamEinstein** [poketwo/poketwo#218]
Hi, I'm a python developer and would like to contribute to poketwo

**Comment by silasary** [comment]
Hi 😄 

I'd recommend starting by picking one of the bugs (https://github.com/poketwo/poketwo/issues?q=is%3Aissue+is%3Aopen+label%3Abug) - #105 seems easy enough

Fork the repo, fix the bug, and send a pull request 😁

**Comment by IamEinstein** [comment]
okay sure
thnx 😄

**Comment by IamEinstein** [comment]
hi @silasary 
I solved it and (hopefully 😅 ) got the correct soln
So this was the old code in [trading.py](https://github.com/poketwo/poketwo/blob/master/cogs/trading.py)
![poketwo-old](https://user-images.githubusercontent.com/63300310/120363615-f9fb3f00-c329-11eb-86c9-61c82ddfd119.png)
And the error can be resolved by changing `mem` to `omem`
![poketwo-update](https://user-images.githubusercontent.com/63300310/120363622-fb2c6c00-c329-11eb-9755-0f1f9880c7c0.png)

**Comment by IamEinstein** [comment]
#219 Pull request made
👍
