### ISSUE TITLE
Error while trying to run bot code in my own computer

### ISSUE THREAD

**Issue by IamEinstein** [poketwo/poketwo#222]
Hi, I'm trying to run poketwo's code on my own computer.
I've added another bot token and DB URI but when I run the code, I get this error
![img](https://cdn.discordapp.com/attachments/849975217429413888/849975541850964008/unknown.png)
What should I do to resolve this

**Comment by WitherredAway** [comment]
Not sure, correct me if I'm wrong but i think you need [this module](https://pypi.org/project/discord-flags/) imported

**Comment by IamEinstein** [comment]
thank @WitherredAway 
Now it doesn't show that error anymore 
But unfortunately, now I get another error
![img](https://cdn.discordapp.com/attachments/846279783834714154/850027392834994226/4f7LBd18PM1JcAAAAASUVORK5CYII.png)
Tbh, I'm pretty sure that this has sm to do with the DB
Although I've added the details of the mongo DB in config.py
I don't quite know how to solve this

**Comment by WitherredAway** [comment]
I'm not sure what the second error is caused by, I'd say wait for Oliver to respond.

**Comment by IamEinstein** [comment]
okay

**Comment by IamEinstein** [comment]
@oliver-ni 
could u tell me what to do to resolve this error

**Comment by kyle-he** [comment]
Issues are not meant for this purpose. If you need help running an instance of the bot, I think you will be better off messaging Oliver on Discord instead.

**Comment by IamEinstein** [comment]
Ok
