### ISSUE TITLE
Pokedex completion reward

### ISSUE THREAD

**Issue by Gapyo** [poketwo/poketwo#226]
Since all of the pokemon are in the bot now, are there any plans to get a reward for completing the dex?

**Comment by Doge-Doge-Dogelol** [comment]
yea it should

**Comment by WitherredAway** [comment]
There is a completion reward. You get **31430**pc from catching all catchable pokemon once. Not to mention that you get more as you catch more of each pokémon.

**Comment by kyle-he** [comment]
I agree that there should be some kind of additional award for completing the dex. Since there are less than 100 people will a fully complete dex, maybe some amount of PC/Shards for catching 1 of every pokemon for each region?

**Comment by scarhoops** [comment]
If you hamood but you don't bababooey does that really mean that you can chu papi munanu?
