### ISSUE TITLE
Missing moveset for Scorbunny/Raboot

### ISSUE THREAD

**Issue by kodywhite** [poketwo/poketwo#227]
**Describe the bug**
when using the p!moveset command for scorbunny/raboot (havent tested with Cinderace but I'd imagine it follows suite), it returns with no known moves, nor moves to learn.

**To Reproduce**
1. Select Raboot
2. use command p!moveset
3. console returns with embed showing no moves. (pic attached)

**Expected behavior**
Embed should populate with moves that can be learned by this pokemon.

**Screenshots**
![image](https://user-images.githubusercontent.com/85371760/120862957-6c993400-c54f-11eb-894a-cd754c11fa64.png)

**Additional context**
I have verified with other pokemon in my collection that my moveset will populate with other selections, just not this one. 
If it is relevant, this Raboot was initially my starter (Scorbunny).

**Comment by bobbers0n** [comment]
Moves for Generation 8 Pokémon are not implemented in Pokétwo yet.

**Comment by kodywhite** [comment]
> Moves for Generation 8 Pokémon are not implemented in Pokétwo yet.

Ah, what a fool I am. 
Thank you.
