### ISSUE TITLE
We can trade nothing also.

### ISSUE THREAD

**Issue by Pro720** [poketwo/poketwo#228]
Describe the bug- We can trade nothing while trading

To Reproduce - start a trade with any of your friend or account. Don't add anything to trade confirm trade from both sides

Expected behavior - It should say to add something or cancel the trade

![Screenshot (1622)_LI](https://user-images.githubusercontent.com/74492472/120886765-3c17cf80-c60d-11eb-8e65-59140bae4600.jpg)

**Comment by WitherredAway** [comment]
This isn't a major bug, if a bug at all, so I'll close this issue now. Thanks for the report tho!
