### ISSUE TITLE
Summer themed pokemon 

### ISSUE THREAD

**Issue by MajimMamba** [poketwo/poketwo#245]
I'd like to see some summer themed event pokemon, some ideas would be pokemon just wearing some "summer" apparel.

**Comment by william0421-r** [comment]
same

**Comment by wizard7176** [comment]
![Uploading Untitled design (1).png…]()
summer weedle lol

**Comment by wizard7176** [comment]
![Untitled design (1)](https://user-images.githubusercontent.com/78194336/123664050-a01c6500-d854-11eb-8df7-7bd901dd4c67.png)

**Comment by aweeeeee** [comment]
Question to developers:

do you love women

**Comment by furevi** [comment]
we want poketwo online!!!

**Comment by OliverIsBadGay** [comment]
Poketwo Is Gay

**Comment by RedVertigoFox** [comment]
you made a whole ass account just to say that

**Comment by OliverIsBadGay** [comment]
lol

**Comment by OliverIsBadGay** [comment]
its gay bcuz its off for like 8 hours now

**Comment by wizard7176** [comment]
I really hope gen 8 moveset is coming

**Comment by FranieLUA** [comment]
yoooooooo sheesh fuck me

**Comment by wizard7176** [comment]
thats why its such a bug update?

**Comment by OliverIsBadGay** [comment]
sure

**Comment by FranieLUA** [comment]
bro poketwo been off for 8 hours they said they will fix this wtf

**Comment by wizard7176** [comment]
probably a big update

**Comment by OliverIsBadGay** [comment]
i hope so, maybe not

**Comment by RedVertigoFox** [comment]
for conversations, please go to #general

**Comment by wizard7176** [comment]
sure

**Comment by oliver-ni** [comment]
This is not a place for conversation.
