### ISSUE TITLE
Rewrite 

### ISSUE THREAD

**Issue by william0421-r** [poketwo/poketwo#247]
we want to see the rewrite can u work on it faster @oliver-ni thx it is just a question

**Comment by Rothuith** [comment]
fuck you honestly

**Comment by FranieLUA** [comment]
cock n ball torture

**Comment by FranieLUA** [comment]
cock n ball torture

**Comment by FranieLUA** [comment]
cock n ball torture

**Comment by FranieLUA** [comment]
cock n ball torture

**Comment by FranieLUA** [comment]
cock n ball torture

**Comment by FranieLUA** [comment]
cock n ball torture
