### ISSUE TITLE
Auction

### ISSUE THREAD

**Issue by william0421-r** [poketwo/poketwo#249]
**Is your feature request related to a problem? Please describe.**
let us bid in other sever not only at poketwo os 

**Describe the solution you'd like**
the Solution I'd like is to change the I'd like to make it to let us auction in the outside of the main server
 if ctx.guild.id != 716390832034414685:
return await ctx.send(
"Sorry, you cannot start auctions outside of the main server at this time."
@oliver-ni please take a look of this
**Additional context**
N/A

**Comment by FranieLUA** [comment]
yeahh that code sucks dick
