### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by william0421-r** [poketwo/poketwo#251]
**Is your feature request related to a problem? Please describe.**
On README.md there is a other side said Other it add egg hatching achievements and weekly quests also lot more generally but I don't see where all those things at I only seen daily and badges 

**Describe the solution you'd like**
- Other
	- Daily/weekly quests with rewards
	- Achievements/profile badges
	- Egg hatching/breeding
	- Generally more customization options

**Additional context**
Yes please add the weekly quests and egg hatch also the achievement
@oliver-ni take a look of this

**Comment by WitherredAway** [comment]
if you re-read README.md, you'll notice that it says "Roadmap
I'm looking to add the following major features to the bot, in addition to QoL fixes and small updates:" which means they're *planned* features. Although it is a little outdated since Gen8 and Quests are already out.
