### ISSUE TITLE
help command - module 'discord.ext.commands.converter' has no attribute '_Greedy'

### ISSUE THREAD

**Issue by builderpepc** [poketwo/poketwo#252]
**Describe the bug**
When the command `(prefix)help pokedex` (or with any of the aliases of the `pokedex` command) is used, the message of an AttributeError appears:
`module 'discord.ext.commands.converter' has no attribute '_Greedy'`

**To Reproduce**
1. Set up PokeTwo on a server.
2. Use the command `(prefix)help pokedex` or `(prefix)help d`.

**Expected behavior**
PokeTwo should give an explanation of the pokedex command, or at least a user-friendly error message.

**Screenshots**

![image](https://user-images.githubusercontent.com/49398322/124709138-26761e00-dec9-11eb-9988-14551617e5e2.png)

**Additional context**
I have tested this on multiple servers to make sure it's not somehow a problem with my own server.

**Comment by ShashankKumarSaxena** [comment]
I guess this error is raised by flag parsing. That module uses this type of converter.

**Comment by Mithaaii** [comment]
i like how i got mithaaii banned in the cross fire

**Comment by builderpepc** [comment]
Closing this issue, it looks like PR #268 fixed this.
![image](https://user-images.githubusercontent.com/49398322/130299300-e02d0357-5572-4b54-9c05-7942668a8717.png)
