### ISSUE TITLE
How To Host?

### ISSUE THREAD

**Issue by WolfGamer2** [poketwo/poketwo#253]
How Do I Host This? @oliver-ni @prabowo02 @kyle-he @markman123 @silasary

**Comment by silasary** [comment]
You shouldn't be hosting your own copy, you should instead invite the official bot to your server: https://invite.poketwo.net/

**Comment by oliver-ni** [comment]
As silasary said, we don't provide support for self-hosting. You can do it, but at your own risk, and I'm not going to walk you through the process. The bot has a couple moving parts.

Additionally, please don't tag a bunch of random people. I'll be closing this issue.
