### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anshtyagi0** [poketwo/poketwo#254]
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<Trading.clear_trades() done, defined at /home/runner/poketwo/cogs/trading.py:27> exception=TypeError("create_redis_pool() missing 1 required positional argument: 'address'")>
Traceback (most recent call last):
  File "/home/runner/poketwo/cogs/trading.py", line 28, in clear_trades
    await self.bot.get_cog("Redis").wait_until_ready()
  File "/home/runner/poketwo/cogs/redis.py", line 23, in wait_until_ready
    await self._connect_task
  File "/home/runner/poketwo/cogs/redis.py", line 15, in connect
    self.pool = await aioredis.create_redis_pool(**self.bot.config.REDIS_CONF)
TypeError: create_redis_pool() missing 1 required positional argument: 'address'
message="Starting with shards [0] and total 1" cluster=Arbok levelname=INFO name=poketwo
message="logging in using static token" levelname=INFO name=discord.client
message="Failed to connect for shard_id: 0. Retrying..." levelname=ERROR name=discord.shard

**Comment by oliver-ni** [comment]
We don't provide support for self hosting.

**Comment by anshtyagi0** [comment]
please.
I need help because i am working on shard for first time

**Comment by Mithaaii** [comment]
> please.
> I need help because i am working on shard for first time

https://www.youtube.com/watch?v=L3yHWOFDXIo&ab_channel=LeeandLie

**Comment by oliver-ni** [comment]
> > please.
> 
> > I need help because i am working on shard for first time
> 
> 
> 
> https://www.youtube.com/watch?v=L3yHWOFDXIo&ab_channel=LeeandLie

It's a great cover. But please don't post off topic things here.
