### ISSUE TITLE
p!pokemon command not working

### ISSUE THREAD

**Issue by ProphecyXXI** [poketwo/poketwo#263]
The p!pokemon command is supposed to list all the pokemon you have and it worked once for me and another member but since then hasn't worked for anyone despite multiple resets to the bot. It's the only command that does actually nothing and it makes the bot very frustrating to use, especially when you get to larger amount of pokemon. Anyone have a fix?

**Comment by oliver-ni** [comment]
Was a temporary issue fixed by 7a7ea572f1b8a611f5b166436f708d5d545f81ea.
