### ISSUE TITLE
box and trading issue

### ISSUE THREAD

**Issue by sohum123451** [poketwo/poketwo#266]
i am frustrated with the box's rewards in ultra box its been a month i am getting 400,800 coins and not even a normal pokemon i request to change the box rewards 
**Additional context**
also there is a bug in trade it dose not show  that we have accepted trading also what we have added

**Comment by WitherredAway** [comment]
This is just dependant on luck and i don't think there are any plans to change the box rewards, unfortunately, as they are easy to obtain.
