### ISSUE TITLE
p!help dex causing errors

### ISSUE THREAD

**Issue by pikaninja** [poketwo/poketwo#267]
**Describe the bug**
When doing p!help dex, an error `module 'discord.ext.commands.converter' has no attribute '_Greedy'` occurs

**To Reproduce**
type `p!help dex`

**Expected behavior**
it sends the help for the command dex

**Screenshots**
![image](https://user-images.githubusercontent.com/38714028/126663281-ea0068eb-46f6-4955-b528-5c4d85b03b2d.png)

**Additional context**
appears to only be dex? unsure about the exact cause of this issue but i tested market/ping/battle which worked fine

**Comment by pikaninja** [comment]
actually, when looking into this, it appears to be all the flag commands`p!pokemon`, `p!market search`, `p!auction search`, etc

**Comment by pikaninja** [comment]
Update, when testing on my bot, it appears it originates from helpcommand. get_command_signature, which breaks when encountering flag commands

**Comment by pikaninja** [comment]
Further update, this is caused by a change in 2.0 making [this code](https://github.com/XuaTheGrate/Flag-Parsing/blob/master/discord/ext/flags/_command.py#L92) error

**Comment by pikaninja** [comment]
Solution will either be to monkey patch the error, or subclass the flags to create a fixed version, i will pr the latter one when i can, but its going to be up to oliver to accept my pr or just monkeypatch it(which is objectivly worse but also cleaner)

**Comment by pikaninja** [comment]
so uh, i didn't notice #252 exists which is a duplicate/mines a duplicate so sorry :(, but yeah i pull requested a fix at https://github.com/poketwo/poketwo/pull/268

**Comment by WitherredAway** [comment]
Will close this since it has been fixed.







hi pika
