### ISSUE TITLE
shop bug

### ISSUE THREAD

**Issue by 3favoritepower** [poketwo/poketwo#274]
when you do p!shop then p!shop page (1-7)

it will say “Converting to "int" failed for parameter "page".”

pls fix it

**Comment by WitherredAway** [comment]
not a bug, do p!shop (1-7)

**Comment by 3favoritepower** [comment]
yea its a bug i cannot do it it just said that word
“Converting to "int" failed for parameter "page".”

**Comment by 3favoritepower** [comment]
when i do that

**Comment by 3favoritepower** [comment]
![Uploading 6AE3A604-48F0-4DFC-B4F3-DCD5683D988F.png…]()

**Comment by WitherredAway** [comment]
don't do "p!shop page (1-7)", that's not how it works. try "p!shop 1-7" (example: p!shop 4) and that'll work

**Comment by 3favoritepower** [comment]
oh thx
