### ISSUE TITLE
Oh no my strongest pokemon get a bug

### ISSUE THREAD

**Issue by 3favoritepower** [poketwo/poketwo#275]
jDescribe the bug
Some pokemon learn no move and has no movesets
To Reproduce
you cannot really re produce. Just do p!moves or p!move set it learns nothing

Expected behavior
its should show what move it can learn and what move it can learn by leveling up

Screenshots
![82C9A661-CB61-4E38-99CD-A36B4E6A8415](https://user-images.githubusercontent.com/88326794/128040910-f527a94f-2986-4738-a2f5-257a2cc9d768.png)

Pls fix this bug and give it to my dreepy/drakloak since i spend a tone of pokecoins on it (around 500 poke coins) just on rare candies. If you still cannot fix it just give me a dreepy (any iv and level) id be happy :)

**Comment by WitherredAway** [comment]
Gen8 pokemon don't have moves currently, but they're planned. The developer knows and they'll be out soon.

On the other hand, Event pokemon don't (and won't) have moves.

**Comment by 3favoritepower** [comment]
oh i didint know that thx for cooling me down

**Comment by 3favoritepower** [comment]
also btw dreepy / drakloak is the best poke that i get legitly. The strongest pokemon i have wich is a level 75 medicham that i get from a box for voting so thats not a legit (since i was expecting to give me poke dolars)

**Comment by michaelsong4399** [comment]
Closing issue because there are multiple duplicates. The battling system would probably get a major fix/rework soonTM.

And about dreepy being the best poke, you should probably discuss it with the folks in #battling-talk on Poketwo Discord Server instead. Thanks!
