### ISSUE TITLE
Bot offline

### ISSUE THREAD

**Issue by kautsar531** [poketwo/poketwo#276]
hey why is the bot on my server offline while on another server it's online please fix it

**Comment by YunanYum** [comment]
In My server Poketwo is off, plis help

**Comment by JulioV17** [comment]
Same in my server, has been off for about 5 days

**Comment by michaelsong4399** [comment]
Bot is currently experiencing partial outage while issues are being fixed. Please refer to #status in Poketwo Official Server for status updates and details. In the meantime, feel free to use the bot in the official server. Thanks.
