### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by oliver-ni** [poketwo/poketwo#28]
Achievements for accomplishing certain tasks.

Example:
* collector — have 100 of the same species
* great collector — have 500 of the same species
* ultra collector — have 1000 of the same species

**Comment by KayneB17** [comment]
Would this just be within the bot or discord aswell? Like automatic roles that are given to said people who complete each collector rank.

**Comment by michaelsong4399** [comment]
Badges feature added in https://github.com/poketwo/poketwo/commit/f4f31c94ea09b37030b99dc1ce10c05cb9c2ae32.
