### ISSUE TITLE
Search by IV Range

### ISSUE THREAD

**Issue by Nilint1** [poketwo/poketwo#284]
**Is your feature request related to a problem? Please describe.**
I want to be able to see all my pokemon or pokemon in the shop at a range.  Example: 50-100 IVs.

**Describe the solution you'd like**
Allow the --iv flag to parse a range of numbers.  Would be separated by a hyphen (-) for a range and a comma (,) for specific ivs to search for.

**Additional context**
There would need to be logic to parse any order.  So if a user gives the larger, or lesser number first, it still works.
Examples:
```
p!p --iv 60-100
p!p --iv 75 -100
p!p --iv 50 - 60
p!p --iv 100-80
p!p --iv 50, 60, 70
p!p --iv 43,50,20
```

**Comment by WitherredAway** [comment]
you can already do that with for example `--iv > 50` for 50-100, `--iv > 50 --iv < 60` for 50-60. but i do agree, that way it would be a lot more convenient.
