### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by oliver-ni** [poketwo/poketwo#29]
Daily/weekly tasks to earn special rewards.

Example:
* Evolve 3 Fire Type Pokemon [0/3]
* Catch 2 Nidoran♀️ [0/2]
* Gain 25 levels on any pokemon [9/25]

**Comment by KayneB17** [comment]
Special reward Ideas.

Each reward is 250c

For all rewards each day you get an extra 500? So if u had for example 4 challenges per day, you can get a total of 1500 for the day.

With weeks maybe if you complete all your weekly rewards you get 10,000?

**Comment by Shirra2006** [comment]
### Maybe adding some daily quests like:

- Trade pokemons (Example: _Trade 5 Ghost type pokemons [0/5]_)

- Catch pokemons with a certain type of nature (Example: _Catch 5 Pokemon with Bashful nature [0/5]_)

- Buy some items (Example: _Buy Quiet Mint [0/5]_)

- Mega some pokemons (Example: _Mega 5 pokemons [0/5]_)

- Buy pokemons (Example: _Buy 5 pokemos  [0/5]_, _Buy 5 Water Type Pokemons [0/5]_)

### And some weekly quests like:

- Catch a certain type of rarity (Example: _Catch a Legendary Pokemon [0/1]_, Catch a Shiny Pokemon [0/1])

- Catch a certain type of pokemon with a certain nature (Example: _Catch 5 Squirtles with Bashful nature [0/5]_, _Catch  5 Water Type pokemons with Bashful nature [0/5]_)

-Evolve pokemons through certain ways (Example: _Evolve 10 pokemons through trading  [0/10]_, _Evolve 5 pokemons with Evolution Stones  [0/5]_)

- Mega a certain type or a certain pokemon( Example: _Mega 5 Blastoise [0/5]_, _Mega 10 Water Type pokemons  [0/10]_)

- Use form changing items (Example: _Use 5 Red Nectar  [0/5]_)

- Trade a certain type or certain pokemon (Example: _Trade 10 water type pokemons [0/10]_, _Trade 5 Blastoise  [0/5]_)

- Buy a certain pokemon (Example: _Buy 5 Blastoises [0/5]_)

**Comment by ks129** [comment]
Is this ready to be done or this have to wait for bot rewrite?

**Comment by michaelsong4399** [comment]
Feature added in https://github.com/poketwo/poketwo/commit/f4f31c94ea09b37030b99dc1ce10c05cb9c2ae32.
