### ISSUE TITLE
Ice Stone Evolutions

### ISSUE THREAD

**Issue by Kingslayer047** [poketwo/poketwo#290]
I own an alolan vulpix and the requried way to evolve it is an ice stone  but the currently shop has no item called the ice stone.

An Ice Stone can be added to shop to evolve pokemons to their next form/evolution leaving the 8th gen moves out of scope for now.

**Comment by WitherredAway** [comment]
Not sure about when this issue was created but right now ice stone does exist (understand p!shop 2) and costs 150 pc
