### ISSUE TITLE
Market shinies and leg 

### ISSUE THREAD

**Issue by Preetampa** [poketwo/poketwo#292]
There has been recently some problem in market that we can't buy the pokemons listed in market like some shinies are listed for 18k or 25k but when we buy it shows couldnt find the Pokemon so pls fix it

**Comment by michaelsong4399** [comment]
Could you please provide a picture of that market bug? Thanks.

**Comment by unknownking31** [comment]
> Could you please provide a picture of that market bug? Thanks.

Ig they are talking about duped mons which are stuck in market rn and couldn't be bought

**Comment by karmaiii** [comment]
selling autocatch for 2m pc dm me at Nyctovity#2204

**Comment by karmaiii** [comment]
the git hub link for the autocatcher

**Comment by karmaiii** [comment]
selling autocatcher for 2m pc dm me at Nyctovity#2204

**Comment by karmaiii** [comment]
selling autocatcher for 2m pc dm me at Nyctovity#2204

**Comment by karmaiii** [comment]
sold 30 ac

**Comment by karmaiii** [comment]
ez 60m

**Comment by karmaiii** [comment]
sale ended btw

**Comment by karmaiii** [comment]
selling autocatcher for 2.5m pc dm me at Nyctovity#2204

**Comment by WitherredAway** [comment]
These duped market listings have been patched
