### ISSUE TITLE
Adding vote boxes in trade

### ISSUE THREAD

**Issue by Suriya2340K** [poketwo/poketwo#293]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**
Hi Oliver we know u working hard can u do this request for our fans we are getting scammed for buying vote boxes if get something worth in it the box owner is running can u help in that we need to add vote boxes in trade this is our request 
Thank you Oliver.

**Comment by WitherredAway** [comment]
Vote boxes are exclusive to voting (hence the name) and will not be made tradable
