### ISSUE TITLE
Got Banned Falsely

### ISSUE THREAD

**Issue by emispusiii1** [poketwo/poketwo#294]
Hello, i got banned from using the bot today for autocatching which I didn't.
I got a dm saying my vote timer refreshed and was like yeah ima vote again, i went ahead to vote and when i opened the box it said "Account Suspended
Your account was found to be in violation of Pokétwo rules and has been permanently blacklisted from using the bot.
Reason
autocatching"

Was pretty confused since i dont recall myself using an auto catcher or other forbidden tools and what makes it even worse is that i spent $20+ for shards and supported the bot.

Maybe it was an error since i trade a lot and receive a lot from friends in my server and it might've triggered something in the ban system. 

I dont expect anything since this already seems like a final decision but i would appreciate if someone would take a look at this or my appeal maybe. A second chance would be appreaciated considering i didnt do anything in the first place and support the bot by voting and donating.

Im gonna provide a screenshot of the message and my reaction.

![Bild_2021-09-05_154905](https://user-images.githubusercontent.com/90141922/132129281-061b0284-d668-4ab9-b339-d502243d97e8.png)

![Bild_2021-09-05_155200](https://user-images.githubusercontent.com/90141922/132129356-23d9f32a-eb35-43ee-a3b2-14c620182b32.png)

My discord ID : 704186294074343504

**Comment by michaelsong4399** [comment]
Please submit an appeal request [here](https://docs.google.com/forms/u/0/d/e/1FAIpQLSeXCWuCloEtUrwaCUwfLsFvyg-wATOZsvG4SOXEBA2adgkqvA/viewform). A staff member will let you know if your appeal has been approved. Thanks.
