### ISSUE TITLE
commands are not working properly

### ISSUE THREAD

**Issue by kshitij1127** [poketwo/poketwo#295]
we have poketwo in our server. Although it is nice, from the past 3 days it is not working properly 
**like it is not taking in commands such as p!balance and p!info. when these commands are hit, it is not displaying any image.**

i hope that this will be resolved as soon as possible. 

we are a big fan of poketwo and hope all issues are resolved as soon as possible

**Comment by Suero152** [comment]
People without a profile picture are facing this problem, try to get yourself a profile picture.

**Comment by kshitij1127** [comment]
yeah thanks for the advice. Anyways, the issue has been resolved. thanks.
