### ISSUE TITLE
Can't increase the IV of my pokemon.

### ISSUE THREAD

**Issue by PacficCoder** [poketwo/poketwo#296]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by PacficCoder** [comment]
I want to increase the IV of my pokemon but there is not a feature to increase IV.

**Comment by sourabh-cmd** [comment]
i need some pc sourabh#6200 plz 2000 pc

**Comment by sourabh-cmd** [comment]
sourabh#6200

**Comment by sourabh-cmd** [comment]
sourabh#6200

**Comment by oliver-ni** [comment]
IV is not changeable.
