### ISSUE TITLE
pokemon

### ISSUE THREAD

**Issue by sourabh-cmd** [poketwo/poketwo#297]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sourabh-cmd** [comment]
i pay marshadow for 10k pc but it not added plz check sourabh#6200

**Comment by michaelsong4399** [comment]
Please Discord message one of the moderators with a more detailed explanation and a photo proof. Thanks.
