### ISSUE TITLE
Poketwo isn't working in my server

### ISSUE THREAD

**Issue by YagamiGaming** [poketwo/poketwo#298]
**Describe the bug**
The bot hasn't been working in my server for past 1hr 30 mins . It says that the bot ahs been disabled or been down for some updates . It worked well before this message .

**To Reproduce**
I tried the use all the commands but it's still the same . I reinvited the bot too , but it's still the same. 

**Expected behavior**
I expected for it to work in 5 to 10 mins

**Screenshots**
![Screenshot_2021-09-07-23-40-52-33_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/89197367/132391738-fe401938-0957-4b97-81b1-6db2135527b1.jpg)

**Comment by Chappers123** [comment]
I have the same issue

**Comment by michaelsong4399** [comment]
Updates and maintenance have been going on intermittently for the last few days. Check out #status in official Poketwo server for more details and expected bot downtimes. If the bot is unavailable in your server, feel free to use the official Poketwo server instead. Thanks.
