### ISSUE TITLE
Poketwo is stopped working in my server

### ISSUE THREAD

**Issue by Chappers123** [poketwo/poketwo#299]
![AFFF27B2-DB18-4B0E-9626-3628E44F686A](https://user-images.githubusercontent.com/90309322/132466715-ff2159cf-81ef-48a5-a95e-c7ed18b44a2a.png)
**Describe the bug**
A clear and concise description of what the bug is. For the last 8 hours when ever we enter any commands. It says the bot is disabled and to check updates and status. 

**To Reproduce**
Steps to reproduce the behavior.
Have entered all commands and the same message appears, tried with multiple people

**Expected behavior**
I expect it to work as normal
**Screenshots**
If applicable, add screenshots to help explain your problem. I can’t add screenshot from my mobile 

**Additional context**

**Comment by Chappers123** [comment]
I have also removed the bot and invited again but still have the same issue

**Comment by nalhub** [comment]
I have the same issue with my server. We have uninvited and invited the bot multiple times, but it still says that the bot is disabled.

**Comment by 1Asher-debug** [comment]
Hi I am Light And My Account Is Banned Because I Joined Plasma HQ SERVER And My Work Wasted So My Request Is Please Unban My Account My Account Is Light Yagami#2358
