### ISSUE TITLE
My Poketwo account is disabled Because I joined plasma hq

### ISSUE THREAD

**Issue by 1Asher-debug** [poketwo/poketwo#300]
My Poketwo account is disabled Because I joined plasma hq and my whole work Wasted please Unban My Account 
Light Yagami#2358

**Comment by WitherredAway** [comment]
You can appeal [on this form](https://docs.google.com/forms/u/0/d/e/1FAIpQLSeXCWuCloEtUrwaCUwfLsFvyg-wATOZsvG4SOXEBA2adgkqvA/viewform), posting here isn't going to help.
