### ISSUE TITLE
Setup new version with conventional commit syntax for automatic CHANGELOGs

### ISSUE THREAD

**Issue by mahyarmirrashed** [poketwo/poketwo#301]
**Describe the solution you'd like**
If you are planning to rewrite the bot in TypeScript using DiscordJS library, I would recommend that you start using conventional commits through commitizen so that you can generate CHANGELOGs automatically. Feel free to add me on Discord (darling#9495) if you want to get in touch.

**Comment by karmaii** [comment]
fuck u all

**Comment by karmaii** [comment]
dacanine fuck you because of you I lost my shiny shaymin u fucking ac

**Comment by WitherredAway** [comment]
Damn you need to have a different level of commitment towards toxicity to do this shit on GitHub. Take this elsewhere

**Comment by karmaii** [comment]
> Damn you need to have a different level of commitment towards toxicity to do this shit on GitHub. Take this elsewhere

shut up simp

**Comment by karmaii** [comment]
i would snap dacanine 's head off and feed it to mars

**Comment by WitherredAway** [comment]
Nobody's seeing these on the server in #github, I'm deleting the messages as they come, so stop trying to entertain yourself 🙏

**Comment by karmaii** [comment]
> Nobody's seeing these on the server in #github, I'm deleting the messages as they come, so stop trying to entertain yourself 🙏

son of a bitch hope u die a dog's death

**Comment by WitherredAway** [comment]
Thank you for the kind words

**Comment by karmaii** [comment]
i will kill every one from tt

**Comment by WitherredAway** [comment]
👍

**Comment by karmaii** [comment]
> 👍

shove ur dick in me

**Comment by karmaii** [comment]
i will slice every ones throt

**Comment by karmaii** [comment]
in tt ofc

**Comment by karmaii** [comment]
dacanine is a nigger

**Comment by karmaii** [comment]
Wither u r a nigger tooo

**Comment by karmaii** [comment]
mars i want you, and de skin u and feed ur skin to dogs

**Comment by karmaii** [comment]
Wither i love u

**Comment by WitherredAway** [comment]
you do realize that you're talking to yourself right? literally nobody is seeing your messages :poliwhirl_eyes:

**Comment by karmaii** [comment]
> you do realize that you're talking to yourself right? literally nobody is seeing your messages :poliwhirl_eyes:

ik

**Comment by WitherredAway** [comment]
> Wither i love u
I'll keep this message tho.

**Comment by karmaii** [comment]
i want to bite ur dick off and feed it to dacanine

**Comment by karmaii** [comment]
> > Wither i love u
> > I'll keep this message tho.

ty dad

**Comment by karmaii** [comment]
hmm

**Comment by karmaii** [comment]
https://www.youtube.com/watch?v=kn5OUBks7UM&ab_channel=Jeanelleats

**Comment by mahyarmirrashed** [comment]
So, um, this makes me really uncomfortable. That is really abusive language and I have reported you to GitHub. I hope the maintainers of the project will still see and read my original message.

**Comment by michaelsong4399** [comment]
I am reopening this issue for the moment until Oliver checks it out. Thanks.

**Comment by karmaii** [comment]
> So, um, this makes me really uncomfortable. That is really abusive language and I have reported you to GitHub. I hope the maintainers of the project will still see and read my original message.

die
