### ISSUE TITLE
I think checkout button is broken

### ISSUE THREAD

**Issue by Sevensins13** [poketwo/poketwo#302]
When attempting to checkout the checkout button literally has no reaction whatsoever please help so I may make my purchase.. thank you

**Comment by karmaiii** [comment]
selling auto catcher for 2m pc dm me at Nyctovity#2204

**Comment by karmaiii** [comment]
selling auto catcher for 2m pc dm me at Nyctovity#2204

**Comment by karmaiii** [comment]
selling auto catcher for 2m pc dm me at Nyctovity#2204

**Comment by karmaiii** [comment]
selling auto catcher for 2m pc dm me at Nyctovity#2204

**Comment by GamingwithJJYT** [comment]
> When attempting to checkout the checkout button literally has no reaction whatsoever please help so I may make my purchase.. thank you

having the same issue.

**Comment by WitherredAway** [comment]
Is this issue still persisting?

**Comment by oliver-ni** [comment]
This has since been fixed.
