### ISSUE TITLE
Galarian Pokemon Moves

### ISSUE THREAD

**Issue by CandyKillR** [poketwo/poketwo#303]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by CandyKillR** [comment]
. . .

**Comment by YeyoCoreArt** [comment]
i got a corvnight without moves! how to solve it

**Comment by WitherredAway** [comment]
Moves for gen8 pokemon is planned, but no ETA yet.
