### ISSUE TITLE
PokéTwo bug

### ISSUE THREAD

**Issue by adriangam15** [poketwo/poketwo#305]
This bug is already causing me a lot of problems or ¿for 3 days, pokemon does not appear, we cannot fight or see our p! p, and if we want to perform a command it says the following "The bot's currently disabled. It may be refreshing for some quick updates, or down for another reason. Try again later and check the #status channel in the official server for more details "
![image](https://user-images.githubusercontent.com/91638299/135356410-75060f02-817b-496b-94a1-45608a085c64.png)

**Comment by WitherredAway** [comment]
I doubt it since it's been a while, so i will be closing this issue. Please send a message here if you're still facing the issue.
