### ISSUE TITLE
Bot stopped working in server

### ISSUE THREAD

**Issue by rachel-rad** [poketwo/poketwo#306]
Since the bot went down momentarily at or about 11:00pm est on 9/27/21, it has not come back up in my server. I continue receiving the following message: "The bot's currently disabled. It may be refreshing for some quick updates, or down for another reason. Try again later and check the #status channel in the official server for more details." (The typical message for when the bot refreshes or is down). 

It has now been two full days since the bot has worked in the server and I would really like to be able to continue to use it there. It is my private server and I did not change any permissions for the bot, and there is no one else in that server who could have changed them. I have tried kicking and re-inviting the bot several times over the past few days in an attempt to resolve the issue, but when I use commands nothing happens, and when I try p!ping the above message continues to be shown. 

I would very much appreciate any assistance to resolve this issue so I can continue to use the bot in my server. Thank you so much for your time!

**Comment by oliver-ni** [comment]
Hi!

Do you mind sending me the Server ID of the server in question? I'll take a look.

Thanks,
