### ISSUE TITLE
I would like to contribute to the bot

### ISSUE THREAD

**Issue by leptr** [poketwo/poketwo#310]
Hi, my name is Petar and I have experience coding Discord bots in Python and JavaScript, and as I used Poketwo quite a lot in one of my servers I would really like to help out by contributing to it if you would allow me. Cheers!

**Comment by WitherredAway** [comment]
You're most welcome to contribute if you wish and it would be greatly appreciated! Please follow [the contributing guidelines](https://github.com/poketwo/poketwo/blob/f105206e39e0eabd2e7ca129907336c15e2477dd/CONTRIBUTING.md) for such, cheers
