### ISSUE TITLE
Battle Bug(negative health)

### ISSUE THREAD

**Issue by tigerjade003** [poketwo/poketwo#319]
When Battling, I figured out a bug that allows you to go to negative health and not have your pokemon faint. If your opponent attacks you first(or you have low health) and you use a self-damaging move, such as brave bird, and this is both of your last pokemon, you go to negative health if you make the opponent faint without going to negative health. In this example, the final battle was mega blaziken versus marshadow, when marshadow used close combat, lowering blaziken's health. Then, Blaziken used brave bird(a flying type move with 120 power, but receives recoil damage), and went to negative health, but still won.
![Screenshot 2021-10-24 9 08 07 PM](https://user-images.githubusercontent.com/69996929/138633458-97b41236-3550-45b9-8323-917966420905.png)

**Comment by WitherredAway** [comment]
This will likely be fixed in the upcoming battle overhaul, but that may be a while as the developer has been busy with slash-commands and such. Keep an eye on the bot-updates channel for future updates since there is no ETA as of yet. As such, I will be close this now.
