### ISSUE TITLE
Dueling - When 2 people enter more than 3 Pokemon in `-battle add` or `-duel add`

### ISSUE THREAD

**Issue by ImNimboss** [poketwo/poketwo#321]
**Describe the bug**
In poketwo dueling, it is common practice to try to hide your Pokemon if you're entering your `-duel add` command before your opponent enters his `-duel add` command. Like so:
![image](https://cdn.discordapp.com/attachments/808404030380441600/902448443375628309/Screenshot_2021-10-26_at_12.17.04_PM.png)
When 2 people are in a duel and enter the command with the intention of hiding their Pokemon at the same time on accident (NOT knowing who will enter the command first), then poketwo shows the same message to both trainers as expected. BUT then the duel simply stops working, it terminates and the duel no longer proceeds.
Then the two people are forced to do `-duel x` then start the duel again, pre-decided about who will enter the command first and who won't hide their Pokemon.

**To Reproduce**
Try dueling someone and then typing `-duel add [More than 3 of your Pokemon here]` then have someone else type `-duel add [More than 3 of their Pokemon here]`

**Expected behavior**
Poketwo should show the message to both trainers but not terminate the duel. The duel should go on as normal.

**Screenshots**
I added it in the Describe The Bug section.

**Additional context**
N/A

**Comment by ImNimboss** [comment]
Bump?

**Comment by oliver-ni** [comment]
Battling will be getting a rework soon.
