### ISSUE TITLE
The dex only adds captured pokemons

### ISSUE THREAD

**Issue by Racconccity** [poketwo/poketwo#328]
I do not know if this is a bug or something that is not implemented but the pokemon you buy are not added to the profile or the dex, only the ones you capture in the spawn channels.

![Captura](https://user-images.githubusercontent.com/71821238/139729221-4329687d-42fc-4266-aa92-efff0e89e3f0.PNG)
![Captur1a](https://user-images.githubusercontent.com/71821238/139729223-15c2a2aa-6b38-43e9-9822-4115734448fa.PNG)

This small error should be corrected since I have (like other people) bought pokemon but they are not registered.

**Comment by WitherredAway** [comment]
This is intentional, probably due to catching pokemon being comparitively easier than the games. It is in question tho, it might be changed later on but no final decision on it yet.

**Comment by oliver-ni** [comment]
This is intentional.

**Comment by killnigg** [comment]
![images](https://user-images.githubusercontent.com/93631465/140002778-ee851975-8739-4edf-94a1-324c21490658.jpg)

**Comment by killnigg** [comment]
https://user-images.githubusercontent.com/93631465/140002850-d09697b0-edc4-45d0-b32d-b7a20be1c9d9.jpg

**Comment by killnigg** [comment]
![images](https://user-images.githubusercontent.com/93631465/140002886-3639ea93-c14f-4428-b9a8-f205556007be.jpg)
