### ISSUE TITLE
Ludicolo has only 4 learnable moves

### ISSUE THREAD

**Issue by RyanServi** [poketwo/poketwo#330]
Ludicolo only has 4 learnable moves and doesn’t inherit the learnable moves from his pre-evolutions
This is present on all ludicolos I have seen and tested

**Comment by JustMadeAnAccountForThis1** [comment]
ludicolo has it's generation 6 moveset (Pokémon XY and ORAS)
![ludicolo](https://user-images.githubusercontent.com/93841300/140622337-6b573939-5a31-40b3-bb2b-cfc036a5c6a1.png)

**Comment by WitherredAway** [comment]
This will most likely be fixed with the upcoming rewrite, so I'll close this issue for now
