### ISSUE TITLE
Buff Darkrai's moves

### ISSUE THREAD

**Issue by ImNimboss** [poketwo/poketwo#331]
**Is your feature request related to a problem? Please describe.**
It is, Darkrai has good stats but its moves aren't in sync with its stats.

**Describe the solution you'd like**
Darkrai's main stat is sp. atk, but it's moves sync with normal atk, which results in Darkrai's moves basically just being bad. I would like more sp.atk focused moves for Darkrai

**Additional context**
N/A

**Comment by oliver-ni** [comment]
wip
