### ISSUE TITLE
Moveset empty for Glastrier 

### ISSUE THREAD

**Issue by CyberneTech** [poketwo/poketwo#334]
**Description of the bug**
1. "p!moveset" for Glastrier shows no moves.
2. "p!moves" command gives no response for given pokemon.

**Screenshots**
![image](https://user-images.githubusercontent.com/62790233/141828064-f356f6e8-e5a0-449a-aa78-37bee38791c4.png)

**Comment by WitherredAway** [comment]
Gen8 pokemon don't have any moves yet, they'll be added soon
