### ISSUE TITLE
Dragapult has empty movesets

### ISSUE THREAD

**Issue by birbrain** [poketwo/poketwo#335]
When i try to see what my dragapult's moves are, nothing shows up and same thing for the movesets

![1F02FF2B-5027-4C32-AA69-162DF5E04374](https://user-images.githubusercontent.com/94659842/142551834-13750812-36f5-4554-8f1f-07e1484d2165.jpeg)

i dont know if this is just my problem

**Comment by WitherredAway** [comment]
Gen 8 pokemon don't have moves yet but this is planned, no ETA tho
