### ISSUE TITLE
Pokedex Does Not Update For Evolutions

### ISSUE THREAD

**Issue by baileyfiscus** [poketwo/poketwo#341]
**Describe the bug**
Pokedex does not register a pokemon as "caught" if the method to obtain was evolution.

**To Reproduce**
Evolve any pokemon either by level-up or by p!evolve.

**Expected behavior**
Evolving a pokemon should register it as "caught" in the pokedex.

**Comment by VarMonke** [comment]
It's not a bug, but a feature in the bot. That'd make completing the dex too easy. 
It's the **same** reason why we don't allow released Pokemon to "respawn" in the same channel.

**Comment by oliver-ni** [comment]
This is intended behavior for now.

**Comment by ImNimboss** [comment]
_Evolving_ is different from _catching_, completing the dex is not about having all the Pokemon but about having CAUGHT all the pokemon
