### ISSUE TITLE
A --y (--yes) or -y flag on commands that skips confirmations

### ISSUE THREAD

**Issue by ImNimboss** [poketwo/poketwo#344]
**Is your feature request related to a problem? Please describe.**
Yes, it's a little bit tedious having to press a button when I'm in a hurry, so I'd like a --y or -y flag on the command that skips the confirmation. `p!command -y` is copy-pastable, so it _can_ be a lot faster

**Describe the solution you'd like**
A -y or --y flag on all commands that require confirmation, if the flag is present then poke2 skips the confirmation part.
For example, `p!r l` and then pressing Confirm would become `p!r l --y` or `p!r l -y`

**Additional context**
N/A :>

**Comment by natedawg92** [comment]
I like this idea but feel it may open up the bot to more abuse from selfbots. Having GUI confirmation button will deter most script kiddies from abusing features such as market

**Comment by ImNimboss** [comment]
Correct me if I'm wrong, but isn't there a way to press buttons with selfbots?

**Comment by VarMonke** [comment]
Yes. Essentially a "self-bot" can do anything a normal user on a client can. Although the API endpoint(if there are any) for such interactions are not available to the general public.

**Comment by ImNimboss** [comment]
Ah, fair

**Comment by ImSalad** [comment]
Decent.ig
