### ISSUE TITLE
E m p t y moveset 

### ISSUE THREAD

**Issue by ThatRandomBoi707** [poketwo/poketwo#346]
when I brought Zarude level 60 in the market it doesn’t have any moveset
![E1955FD9-5047-4A99-B973-FCD8682706CB](https://user-images.githubusercontent.com/96508580/147028167-b9652eb8-a6a2-48a7-a225-7d05c4669668.jpeg)

**Comment by VarMonke** [comment]
Not a bug; Zarude is a Generation 8(VIII) Pokémon. In the bot, we don't have move set for that Generation _yet_.
