### ISSUE TITLE
Oliver plz read. SUSPENDED ACCOUNT

### ISSUE THREAD

**Issue by 420hottie2** [poketwo/poketwo#358]
**Describe the bug.

oliver...please

My account was suspended for autocatching...
I don't know if anyone will actually see this... but you guys suspended my account with the reason of autocatching... I have never nor would I ever use any type of autocatching software.  

I have had many friends quite and give me their inventory as gifts and donations. I have earned my things and sold my items as requested within the poketwo guidelines.

I only use a mobile device and am able to do sometimes 3 incense at once. I pride myself on being able to catch my own stuff and collect.  

I honestly don't feel I deserve this after over 8 months of actively using this app.

**To Reproduce**
I have never done anything even close to autocatching

**Expected behavior**
Will you please just review my account and either unsuspend or tell me what really happened. I don't have the capability of running any programs for I don't even own a computer.  Pleas oliver.

**Screenshots**

![Screenshot_20220103-000901_Discord](https://user-images.githubusercontent.com/97074489/148003463-fd570fea-438e-4fa4-8918-bb0321d8f90e.jpg)

**Additional context**
 My email is imaloveyouforever632@gmail.com

**Comment by michaelsong4399** [comment]
Hello, please submit a suspension appeal [here](https://forms.poketwo.net/a/suspension-appeal). Our staff will get to it momentarily.

**Comment by 420hottie2** [comment]
I've been told thay for 2 days... Noone has said anything different I need actually help

**Comment by 420hottie2** [comment]
Ffs why doesn't anything get to oliver... isn't he the lead person making decisions... IM NOT A CHEATER
