### ISSUE TITLE
Not able to select the moves

### ISSUE THREAD

**Issue by kshitij1127** [poketwo/poketwo#361]
**Describe the bug**
While battling in poketwo, the moves are not being executed. Instead, "you selected nothing" message is appearing. 

**Screenshots**
![image](https://user-images.githubusercontent.com/63649035/148738388-b8b00105-1e11-4d30-ab68-2e724670f2d8.png)

**Additional context**
please fix the problem as soon as possible.

**Comment by WitherredAway** [comment]
Is this bug still persisting?

**Comment by WitherredAway** [comment]
It's been a while so I'm fairly certain that this bug has been fixed. Please reopen this issue if not.
