### ISSUE TITLE
Event boxes still dropping

### ISSUE THREAD

**Issue by lightaflame** [poketwo/poketwo#362]
**Describe the bug**
Both naughty and nice boxes are still dropping in select servers. It seems that the time period for the event has ended in addition to the past few commits by Oliver confirming that they are meant to be gone. 

**To Reproduce**
Catching an ice or rock-type in some servers still rewards boxes

**Expected behavior**
No boxes dropping, so as if the event never existed

**Screenshots**
![2022_01_10_02l_Kleki](https://user-images.githubusercontent.com/97438387/148744399-b9e9be8e-1c63-4c19-a500-74cee30a2925.png)
Screenshot is in PST

**Comment by VarMonke** [comment]
The changes have been added. The bot is implementing these through a rolling restart. Please do wait for a while
