### ISSUE TITLE
Suggestion - make an admin role that can tag to 1 or more players for incense buying

### ISSUE THREAD

**Issue by ihemantkumar** [poketwo/poketwo#363]
Suggestion:  There should be a custom admin role in the bot that can be tagged with 1 or more players, who can act as administrator just for bot, for buying or help in buying incense. It's way too awkward to make someone server admin just for this purpose.

We can then make such players responsible to manage pokeTwo bot section on the server

**Comment by natedawg92** [comment]
I second this, we recently had players who wanted to purchase Incense for the server but were unable to without being a server admin

**Comment by WitherredAway** [comment]
This has now been implemented with b3a0bae93ab92c6a6f879c75d9391644a4719a48 such that you can create a role named "Incense" to enable users to buy incenses without the administration permission, and hence i will close this issue now. Thank you for the suggestion!
