### ISSUE TITLE
Poketwo not responding 

### ISSUE THREAD

**Issue by Mizuboo** [poketwo/poketwo#365]
I decided to work on a poketwo leveling on one of my private servers, when I typed in a command and poketwo didn't respond. I tried everything, including removing the bot from the server and readding it and adding friends to verify it wasn't an issue on my end. The bot shows online in my server list, and it works on other servers, but it seems to be completely unresponsive on mine. I first detected the issue around 3pm, and the bot was completely fine yesterday, this being the first time it has happened. It is also not delivering spawns at this point in time.

**Comment by Nyxie89** [comment]
Having the same issue. Assumed the bot was down for maintenance but nits showing as online and there is no mention of it being down anywhere. Guess we just need to wait and see *shrug*

**Comment by LoneWolfisop** [comment]
Ye the bot's ded in many servers atm
