### ISSUE TITLE
Incense burners can be bought but will not spawn pokémon, this bug has occurred twice to me today.

### ISSUE THREAD

**Issue by lxque** [poketwo/poketwo#367]
![image](https://user-images.githubusercontent.com/98238986/150657064-e089f91a-7dd1-4a24-87a9-01d8f21f0439.jpeg) proof of me buying an incense but it not spawning any pokemon

**Comment by WitherredAway** [comment]
I see that you have issued a couple refunds already, but if you face this issue again in the future please DM a mod about it. I also would suggest to lay off on incenses for the time being.

**Comment by Chuktrio** [comment]
Same problem with me also
