### ISSUE TITLE
Voting rewards problem

### ISSUE THREAD

**Issue by amianju** [poketwo/poketwo#371]
So, for the past couple of days voting rewards are getting worse and worse
Like when I first started Poketwo and I was opening the ultra boxes and stuff
I used to get redeems, legendary, mythicals, shinies etc. and when I used to open master box I got a lot of shinies and a lot of good iv legs, myths, ultra beasts
But these days when I open ultra box I get common normal Pokemons with low iv, 800 pc or even sometimes 200 pc and when I open master boxes these days I only get bad iv legendaries or 1600 pc bruh
So please do something about it and make the rewards better

**Comment by oliver-ni** [comment]
Rates have not changed. It's simply luck.

**Comment by amianju** [comment]
Well you might be too lucky ig

**Comment by mike6286** [comment]
Idk this happened to me too. The same exact time. Coincidence maybe?

**Comment by WitherredAway** [comment]
Just luck.
