### ISSUE TITLE
Did not get money when completed a trade. 

### ISSUE THREAD

**Issue by Ullaas123** [poketwo/poketwo#374]
so today afternoon I traded a pokemon for 37,000pc's.... the trade has been executed and pokemon has reached the other user... but when I checked my bal I did not receive the pokecoins.....

I hope you would solve this bug asap 

Thnx

**Comment by WitherredAway** [comment]
Please DM a moderator on the [official server](https://discord.gg/poketwo) and we'll investigate this issue.
