### ISSUE TITLE
Evolved and traded pokemon should count towards pokedex completion

### ISSUE THREAD

**Issue by JebusWookiee** [poketwo/poketwo#375]
It is frustrating to find that my evolved or traded Pokemon do not count towards my dex completion.
I see no real point in leveling each Pokemon to evolve if they do not count towards the dex completion, same with trading. It's nice to have the Pokemon you're missing, but it would be great to be able to see that on the Pokedex.

I'd love for Evolved and traded Pokemon to count towards my dex completion.

**Comment by WitherredAway** [comment]
This place is not meant for conversation.

**Comment by ManiKanta0786** [comment]
**Hello**

**Comment by WitherredAway** [comment]
Duplicate if #341 please check before opening issues. This is intended behaviour for the time being.
