### ISSUE TITLE
Redeems do not work

### ISSUE THREAD

**Issue by Kristy9169** [poketwo/poketwo#376]
I have received a redeem from the daily mystery box, and I have attempted to use it for about a week now. However, whenever I do p!redeemspawn for the pokemon I want, it says "This command is currently disabled. Please check back later."

**Comment by PikaaPiowo** [comment]
samE issue

**Comment by SRAN3458** [comment]
Same issue for me, please enable redeems and market (ik market is working for many people, but it is not working for me)

**Comment by Abdullah-kamal** [comment]
Literally everyone knows its not working since a week and you are typing this now.

**Comment by MRMaffle** [comment]
same issue

**Comment by WitherredAway** [comment]
Redeems are, for the time being, disabled for bug fixing and it'll be back up soon (no ETA)
