### ISSUE TITLE
some of the pokemons dont have any moves when thry should

### ISSUE THREAD

**Issue by Go1Canada** [poketwo/poketwo#380]
Why doesn’t my Galarian Moltres have any moves in poketwo when he does in EVERY OTHER GAME

Ii would like that we had the the moves to this pokemon

And thank you in advance

**Comment by Chuktrio** [comment]
I think that they are generation8 pokemons. They don't have moves right now.

**Comment by pikaninja** [comment]
Should be noted that this has been brought up at least 20 times before, and you(and everyone else) should check past issues before opening new ones

**Comment by WitherredAway** [comment]
Gen 8 pokemon currently don't have any moves. This is known and planned to be added in the future.
