### ISSUE TITLE
Bug while buying incense

### ISSUE THREAD

**Issue by Chuktrio** [poketwo/poketwo#381]
I buyed a incense today in Poketwo bot in my private server. 50 shards were deducted from my balance and it wrote that you have purchased incense. But, it doesn't started spawning pokemons. The incense is also not stopping. 
![image](https://user-images.githubusercontent.com/100832705/156523605-d5d1066e-c949-4a6d-8ed1-1df3fcfd8610.png)
![image](https://user-images.githubusercontent.com/100832705/156523638-77c8739a-5ffc-47d8-81ab-913faae64017.png)
![image](https://user-images.githubusercontent.com/100832705/156523659-b1e8db0a-1531-45a1-8074-03a3f6fd62c3.png)

**Comment by WitherredAway** [comment]
Please DM a moderator on the [official server](https://discord.gg/poketwo) about this if you haven't already so we can issue a refund for you.
