### ISSUE TITLE
Adding forms to the bot

### ISSUE THREAD

**Issue by CapCykes** [poketwo/poketwo#382]
Something that has been bugging me for quite a while is the lack of fusion forms and the newer Pokémon forms. 
For example I have a Lunala and a Necrozma, great! But I can't fuse them into Dawn-Wings Necrozma or Ultra Necrozma, of course. This goes to other Pokémon such as Kyurem and Calyrex.
About the Hisuian forms, it's been quite a while since Legends: Arceus released and we have official artwork, stats, abilities, moves, everything. I'm confused as of why is it taking so long for them to be added into the bot.
Wish the best of luck fixing the redeems command and thank you for reading.

**Comment by WitherredAway** [comment]
Hisuian forms along with other forms are planned, but right now there are other priorities which forms isn't a part of unfortunately. Keep an eye out of #bot-updates on the official server to know about future updates tho!
