### ISSUE TITLE
[Feature Request] Add command to release last pokemon / close account

### ISSUE THREAD

**Issue by colwellkr** [poketwo/poketwo#383]
There should be an optional command to release your last Pokemon or close your account with the bot.

The others in my server still enjoy working with the bot and so I don't want to take anything away from them, but I want it to stop reacting to my messages and I have no interest in playing with it anymore. But at this time there is no way to do that.

There should be a way to opt back out.

**Comment by WitherredAway** [comment]
You can already release the last pokemon with `p!release 0`, `p!release latest` and `p!release l`

As for the other part, you can silence the level up messages using `p!silence` if that's what you meant. I don't see a point in being able to delete your "poketwo account", you can just block the bot and never interact with it again right?

**Comment by oliver-ni** [comment]
Hi,

We currently don't have a command do this. If you would like to delete your account, please email me at support@poketwo.net with your User ID and proof of ownership of your account — I'll take care of it.

We'll keep in mind making this easier for future additions.
