### ISSUE TITLE
it shows me my account is diabled to by a pokemon from market  

### ISSUE THREAD

**Issue by SASUKEEDITS1** [poketwo/poketwo#385]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ninjahunter939** [comment]
>
![D5A5B924-4E58-4FB2-8379-873103B4E9A6](https://user-images.githubusercontent.com/101375452/157788978-270fe1e3-e079-4f9c-9b83-d7bed02e4331.jpeg)
I need an explanation on this. Is it a bug or something? How can I fix this?

**Comment by Siamboi242** [comment]
Same reason

**Comment by SASUKEEDITS1** [comment]
pls fix this glitch

**Comment by pixely5** [comment]
its not letting me buy anything this glitch is so annoying

![Screen Shot 2022-03-16 at 9 10 20 AM](https://user-images.githubusercontent.com/101681629/158496987-c37d666c-7d9d-475e-8398-52143659e808.png)
g

**Comment by WitherredAway** [comment]
It isn't a glitch. It's intentional for newer accounts for but fixing, and it'll be back to normal when it's been fixed. The developer has been rather busy lately, especially with the April deadline for moving to slash commands so please be patient!

**Comment by SASUKEEDITS1** [comment]
No worries, thanks for the update!

**Comment by SASUKEEDITS1** [comment]
pls fix this bug it irritates me i have lost millions of offers in the bug
plss fix it

**Comment by WitherredAway** [comment]
> pls fix this bug it irritates me i have lost millions of offers in the bug plss fix it

This bug was fixed a long time ago i believe, could you provide a screenshot of what the bot shows?
