### ISSUE TITLE
Redeemspawn command is still disabled

### ISSUE THREAD

**Issue by Av32000** [poketwo/poketwo#388]
When i use the `redeemspawn` command, the message <`This command is currently disabled. Please check back later.`> appears since several months. when will the command come back ?

**Comment by Cam2930** [comment]
The following command is temporarily disabled due to money transfer:
• p!redeemspawn

The following commands are temporarily disabled for some accounts:
• p!market add
• p!market buy
• p!auction start
• p!auction bid

The developer is aware of it, and repair is in progress. Please be patient.

**Comment by Av32000** [comment]
Thanks, I'll keep listening.

**Comment by Siamboi242** [comment]
The following command is temporarily disabled due to money transfer:
• p!redeemspawn

The following commands are temporarily disabled for some accounts:
• p!market add
• p!market buy
• p!auction start
• p!auction bid

The developer is aware of it, and repair is in progress. Please be patient.

**Comment by Siamboi242** [comment]
Fixxx

**Comment by WitherredAway** [comment]
The developer has been rather busy, especially due to the April deadline for moving to slash commands i believe

**Comment by Av32000** [comment]
Oh, ok I develop discord bots too and I didn't know there was a deadline to switch to slash commands.

**Comment by WitherredAway** [comment]
> Oh, ok I develop discord bots too and I didn't know there was a deadline to switch to slash commands.

i wasn't able to find any official posts but [this](https://news.ycombinator.com/item?id=28334609) kind of summarizes it.

**Comment by Av32000** [comment]
Thanks, I'll teach myself
