### ISSUE TITLE
Bot Commands Error

### ISSUE THREAD

**Issue by Starlinkboy** [poketwo/poketwo#389]
Bot is down. I appreciate all the additions but please fix this error ASAP so we can get back to playing.
Thanks,
Starlinkboy

**Comment by Cam2930** [comment]
They have been trying hard. Its been more then 10 hours plus give them a break. Coding is hard when there is about 10k lines and trying to see what is it.

**Comment by BigZaZzy** [comment]
> They have been trying hard. Its been more then 10 hours plus give them a break. Coding is hard when there is about 10k lines and trying to see what is it.

True👌

**Comment by Cam2930** [comment]
And there is more to than the bot. Like Family, school ect. He is just like a normal person and any other bot creator. The **best** one

**Comment by LucarioZilla** [comment]
Guys, we are all waiting for the bot to return, 
The devs are working on it, but they have life too, let's let them do that work, now creating useless issues no, please close this issue, this is not a problem and yes a comment

If you want to clarify doubts, then yes, create an issue or go to the PokeTwo server support chat

**Comment by Cam2930** [comment]
I think that's solves this issue/thread
