### ISSUE TITLE
We want redeem back!

### ISSUE THREAD

**Issue by zyzybaka** [poketwo/poketwo#394]
It's been 1 month+ since redeem go on a outage we want it back!

**Comment by ManiKanta0786** [comment]
Ya bro we want redeem's back @Poketwo We want redeem's back 
We Miss Redeems.. So please Work better at Redeem's.....

**Comment by hellmonkehound777** [comment]
yep need them back :(

**Comment by CatalystGamingYT** [comment]
I’ve gotten plenty of redeems but I started playing after they were disabled so I never got a chance to use them. Please activate even if only for a weekend so those with them can spend them.

**Comment by WitherredAway** [comment]
Redeems are currently out of service for bug fixing, but the developer has been rather busy lately (especially with the slash-commands rewrite). Please be patient, it'll be up soon enough! Sorry for the inconvenience.
