### ISSUE TITLE
the pokemons of galar do not know any movement

### ISSUE THREAD

**Issue by MRMaffle** [poketwo/poketwo#399]
**Describe the bug**
I don't know what happened but I bought a shiny cinderace and trained it at the moment I saw that it had no movements I saw that the galar pokemons that I had captured did not have them either

**To Reproduce**
put p!moves in a galar pokemon

**Expected behavior**
show her movements

**Screenshots**
![image](https://user-images.githubusercontent.com/101338790/158685080-f04f6bbc-2c09-4b9c-81ac-378539141b44.png)

**Additional context**
nope

**Comment by WitherredAway** [comment]
Generation 8 pokemon currently do not have moves, it is planned
