### ISSUE TITLE
Commands Not Working 

### ISSUE THREAD

**Issue by CrimsonNeedsHelp** [poketwo/poketwo#402]
**Describe the bug**
Commands P!c, p!i, p!buy (item) isnt working.
Using the commands end up like a regular message.

**To Reproduce**
Steps to reproduce the behavior.
(Unknown currently unknown)
**Expected behavior**
A command appears as a regular message instead of the command 

**Screenshots**
![F0591E28-5F0A-446D-81DF-DD2C50E5EC73](https://user-images.githubusercontent.com/101917565/159108701-1d638546-6f76-43e6-88d8-250365b0cf8b.png)

**Additional context**
(N/A)

**Comment by WitherredAway** [comment]
Seems like the bot had a hiccup. Is it still behaving this way?
