### ISSUE TITLE
No moves in pokémon from galar

### ISSUE THREAD

**Issue by Evaghetti** [poketwo/poketwo#403]
**Describe the bug**
Caught a coalossal and an impdimp that i wanted to train, in both cases when i checked the p!moves both have no moves to learn or be learned

**To Reproduce**
Catch a galar pokémon.

**Expected behavior**
They should have moves to be used.

**Screenshots**
![IMG_20220323_112816.jpg](https://user-images.githubusercontent.com/20467759/159722846-28bd47ff-3020-4ec1-847c-5c65071dd7c4.jpg)

**Comment by Akib-amam** [comment]
> **Describe the bug** Caught a coalossal and an impdimp that i wanted to train, in both cases when i checked the p!moves both have no moves to learn or be learned
> 
> **To Reproduce** Catch a galar pokémon.
> 
> **Expected behavior** They should have moves to be used.
> 
> **Screenshots** ![IMG_20220323_112816.jpg](https://user-images.githubusercontent.com/20467759/159722846-28bd47ff-3020-4ec1-847c-5c65071dd7c4.jpg)

Its not a bug Pokemon from galar haven't been given moves yet.

**Comment by Akib-amam** [comment]
Its not a bug Pokemon from galar haven't been given moves yet.

**Comment by WitherredAway** [comment]
There's no ETA for when they'll be implemented, but the developer has higher priorities right now. They'll be added as soon as possible, sorry for the inconvenience and thanks for your patience
