### ISSUE TITLE
Evolutions

### ISSUE THREAD

**Issue by PicklemeElmo** [poketwo/poketwo#406]
Can there be a command to de evolve Pokémons?

Im a new player so I made a mistake as I did not know to buy a dawn stone before evolving my kirlia. I wanted to evolve gallade but now I have a gardevoir. I feel that not being able to de evolve a Pokémon in this mod is too punishing. I’m sure that others have made this evolution mistake too and it’s really frustrating that it happens

Can there be a new feature where u can de evolve a Pokémon similar to the unmega command?

**Comment by Devanshu19** [comment]
Isn't  that too much for a Pokemon Game? I mean you can't (un/de)evolve a pokemom even in main series pokemon games. To me its unnecessary.

**Comment by lmbalance** [comment]
in the games, you get asked when it tries to evolve and you can stop it. I'm against a general de-evolve command aswell but maybe when leveling up have a button on the lv up message or evolution message that you can react to for lets say 30s to 'cancel' Evolution like in the games.

**Comment by WitherredAway** [comment]
> in the games, you get asked when it tries to evolve and you can stop it. I'm against a general de-evolve command aswell but maybe when leveling up have a button on the lv up message or evolution message that you can react to for lets say 30s to 'cancel' Evolution like in the games.

I agree wholeheartedly
