### ISSUE TITLE
Can't catch Ditto

### ISSUE THREAD

**Issue by BrendonGames** [poketwo/poketwo#408]
**Describe the bug**
I'm trying to catch  a disguised ditto but the bot keeps saying: `That is the wrong pokémon!` 

**To Reproduce**
get a disguised ditto Pokémon and type p!c ditto

**Expected behavior**
Catch Ditto

**Screenshots**
https://cdn.discordapp.com/attachments/803277921929396235/959913656378851347/unknown.png

**Comment by JustMadeAnAccountForThis1** [comment]
It’s an April fools joke so just write the name of the Pokémon “ditto” is copying.

**Comment by BrendonGames** [comment]
oh ok 
now I know at least
