### ISSUE TITLE
Hints haven't changed back

### ISSUE THREAD

**Issue by andromedaeus** [poketwo/poketwo#409]
When using a hint to try to figure out the name of Dreepy, we noticed that, even though the pokemon have become normal again, the hints have not. They still suggest Ditto as per the April Fools prank.

I'm unsure if the devs are aware of this, but I thought I should make this just in case. 
![Screenshot_20220406-190152_Discord](https://user-images.githubusercontent.com/103140520/162039647-b0762199-16e1-407e-bb50-371395841d2d.jpg)

**Comment by WitherredAway** [comment]
This has been addressed, thank you for the report. I will close this issue now.
