### ISSUE TITLE
Bot not responding

### ISSUE THREAD

**Issue by superheri** [poketwo/poketwo#415]
The bot is not responding unless for help command which displays an error like in the following image :
![image](https://user-images.githubusercontent.com/30275781/163575797-c2dfcf1b-568a-4a0d-a4b0-1a282b4f9bb5.png)

**Comment by Mixone-FinallyHere** [comment]
Bot is experiencing an outage currently

You can track bot outages in the poketwo discord channel #bot-outages

You can subscribe notifications on that channel to appear on your server when they happen
