### ISSUE TITLE
I cant use ticket "store purchase"

### ISSUE THREAD

**Issue by cRiiso** [poketwo/poketwo#416]
Well I had a problem where I didn't receive the auction item, so I tried to open a store purchase ticket, but I'm not getting it. A message appears saying "This interaction failed".
I would like a return from the team as I lost 1,100,000.

**Comment by WitherredAway** [comment]
This should be fixed now, thanks for the report

**Comment by WitherredAway** [comment]
Please open another ticket on the support server if you require further support
