### ISSUE TITLE
Market disabled 

### ISSUE THREAD

**Issue by perryboy1084** [poketwo/poketwo#422]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

Anytime i try to buy with the market it tells me its disabled. I really wanted to get this Jirachi but someone else bought it bc im unable to
![Screenshot_20220418-214019_Discord](https://user-images.githubusercontent.com/103977515/163909728-0b48223a-93ed-493e-b310-0d7983663416.jpg)

**Comment by perryboy1084** [comment]
Ive read there was a scheduled time and everything for a bug fix but have seen its been fixed yet my account is still disabled. Everyone else isnt and the only way to get what i want is to have someone else buy it for me. Thats alot of work and trust to do that

**Comment by WitherredAway** [comment]
@perryboy1084 Market is currently disabled for newer accounts (created after Jan 1 iirc) for bug fixing. This will likely be fixed with the upcoming bot rewrite, so the developer can't focus on this issue alone at the moment. It will be back up as soon as possible, sorry for the inconvenience!
