### ISSUE TITLE
Describe the bug A clear and concise description of what the bug is.  To Reproduce Steps to reproduce the behavior.  Expected behavior A clear and concise description of what you expected to happen.  Screenshots If applicable, add screenshots to help explain your problem.  Additional context Add any other context about the problem here.

### ISSUE THREAD

**Issue by Saks7** [poketwo/poketwo#424]
I can't buy pokemon in the store it just tells me that my account is deactivated and to come back later
![CD209C9C-4947-40E3-973A-12CF0E5F089C](https://user-images.githubusercontent.com/104185320/164784440-a597f6b2-be48-4209-9f6d-1be23185a9fd.png)
   
   I can't buy pokemon in the store it just tells me that my account is deactivated and to come back later

**Comment by WitherredAway** [comment]
Hey there! Sorry for the inconvenience, but market (for newer accounts) are currently disabled for bug fixing. This will be fixed with the upcoming bot rewrite, so the developer can't focus on this issue alone at the moment. It will be back up as soon as possible!
