### ISSUE TITLE
Unable to use Dreepy's moves

### ISSUE THREAD

**Issue by Kasv113** [poketwo/poketwo#425]
Dreepy and maybe other gen 8 pokemon are unable to to use or learn moves or even view what moves they should be able to learn

**Comment by UnknownUser135** [comment]
Yo wassup guys I am writing this cuz I want to see this comment in GitHub feed channel 
Nvm

**Comment by UnknownUser135** [comment]
Gen 8 pokemons don’t have moves yet such as Zacian, Eternatus, Zamazenta etc
No eta when they will be added

**Comment by UnknownUser135** [comment]
Hi

**Comment by UnknownUser135** [comment]
A b c d

**Comment by UnknownUser135** [comment]
Wassup guys

**Comment by WitherredAway** [comment]
Gen 8 moves are planned for the near future, stay tuned!
