### ISSUE TITLE
Doesn't let me do anything with my starter Pokémon.

### ISSUE THREAD

**Issue by Ratsareamazing** [poketwo/poketwo#426]
When I started playing with Pokétwo, my started Pokémon's ID was 0.  It didn't start much as a problem, but as I caught more Pokémon, and tried doing a command, mostly "p!battle add 0", instead of going to my starter Pokémon, it went to the Pokémon I caught last.  Is there some way to change my starter's ID to something else so I can use it in battle, learn new moves with it, and more?

Type in "p!p" or "p!pokemon" and check if your starter's ID is 0.  (If it's not, then this problem shouldn't affect you).
Then, to see the problem, type in "p!battle <your friend's name>".  Try adding your starter's ID by doing "p!battle add 0" and it'll equip your latest catch rather than your starter.

I expected this to equip my starter so I could use that in battle.

![image](https://user-images.githubusercontent.com/104472171/165415326-85a19911-740c-4931-9e9b-669f224270b9.png)
![image](https://user-images.githubusercontent.com/104472171/165415430-be7a9d31-9352-4a59-bdb3-be2e7e85829c.png)
![image](https://user-images.githubusercontent.com/104472171/165415670-f174d429-6186-41f8-bd4e-db1fed00aa5a.png)

That's about it, just wondering if you could fix it somehow or let me know how to fix it.  Thanks!

**Comment by SuperJedi224** [comment]
do `p!reindex`, that usually fixes the issue with 0-indexed pokemon

**Comment by WitherredAway** [comment]
As jedi suggested, `p!reindex` fixes this issue! Otherwise you can also use `00` to access that pokemon, e.g. `p!battle add 00`. I hope that's helpful, i will close this issue now
