### ISSUE TITLE
SERVER CANNOT JOIN

### ISSUE THREAD

**Issue by Siamboi626** [poketwo/poketwo#430]
**Describe the bug**
I CANNOT JOIN POKETWO MAIN SERVER EVEN I AM NOT MUTED,TIMEOUT EVEN BAN ALSO 
BUT CANNIT JOIN EVEN I HAVE VERFIED MY MAIL AND NUMBER I CANNOT JOIN WHEN I CLICK IT JUST NOT NOTHIMG I CANNOT JOIN PLS HELP 

@POKETWO OWNER 

SERIOUSY BUG

**Comment by WitherredAway** [comment]
What's your ID?
