### ISSUE TITLE
Typo in `anniversary`

### ISSUE THREAD

**Issue by SiddharthShyniben** [poketwo/poketwo#434]
**Describe the bug**
There is a typo in p!anniversary.

> **Anniversary Boxes — 0**
> You will receive an Anniversary Box for each quest you complete. Use **`pannivesary open`** to open boxes for rewards!

**To Reproduce**
Run `p!anniversary`

**Expected behavior**
No typo

**Comment by WitherredAway** [comment]
Thank you for the report 👍
