### ISSUE TITLE
Auction nicknames /Shiny emotes in nicknames

### ISSUE THREAD

**Issue by AlphaXyph** [poketwo/poketwo#438]
Recently people are trying to add the ✨ emote in their pokemon nickname to disguise them as shiny in auction and trades. I know nickname is supposed to be feature but people really get heart broken after having few 100k's loss which is actually not a small amount.

**There can be few ways that you can use to fix this:**
**1.** Remove auction nicknames (this will only work for auction)
**2.** Don't allow users to use emotes as nicknames (i know it hurts but helps a lot)
**3.** Embed shinies with different colour (still not 100% effective cause embedded mons)
**4.** Give shinies p!info a different themed ui which makes them obviously different from others (too much works + too fancy)
**5.** I can't think about good ideas all alone ;-; so you all think about it

Personally i prefer 2nd idea as it's simple and effective :0 but in the end choice is yours and i think you and figure out a better way to fix this.

**Its not a bug but a loop hole people misuse.**

**Comment by WitherredAway** [comment]
This has been taken into consideration and accordingly, nicknames have been removed from showing in the auction info. Thanks for the report!
