### ISSUE TITLE
My hattrem has no moves

### ISSUE THREAD

**Issue by DocMatey** [poketwo/poketwo#439]
So my hattrem doesnt show me any moves when i write either, moves <hattrems number> or moveset <hattrems number>.

I got this hattrem traded from a friend who has played more than i have, he doesnt remember if it was like so for him.

![use this](https://user-images.githubusercontent.com/88498045/172305452-88b166c6-ed14-4b92-aab1-239a462da74c.PNG)

**Comment by WitherredAway** [comment]
Hey there, thanks for the resport! Generation 8 pokemon currently do not have any moves but the developer working hard to implement them as soon as possible!

**Comment by DocMatey** [comment]
> Hey there, thanks for the report! Generation 8 pokemon currently do not have any moves but the developer is working hard to implement them as soon as possible!

oh ok, thank you for the quick reply

**Comment by WitherredAway** [comment]
Np!
