### ISSUE TITLE
PokéTwo responds incorrectly to certain help commands in P/DM

### ISSUE THREAD

**Issue by jculpon** [poketwo/poketwo#446]
BUG REPORT (from @jculpon/personal, not related to xgoogle/closed source stuff)

**Describe the bug**
Per title: PokéTwo responds incorrectly to certain help commands in P/DM. The bot should not return None/NoneTypes for bare versions of commands.

Here is a P/DM log between myself (version of Discord account on the PK2 Discord) from yesterday:
peri — Hier à 09:51
p!catch
Pokétwo
BOT
 — Hier à 09:51
p!catch
Catch a wild pokémon.
Signature
p![catch|c] <guess>
peri — Hier à 09:51
p!c diglet
peri — Hier à 14:07
p!catch dugtrio
peri — Aujourd’hui à 20:44
p!help 
Pokétwo
BOT
 — Aujourd’hui à 20:44
'NoneType' object has no attribute 'me'
p!catch
Catch a wild pokémon.
Signature
p![catch|c] <guess>
'NoneType' object has no attribute 'me'

**To Reproduce**
STRs are described by the log, exact replay of that transcript results in same error on my Discord Server as in PM/DM.

**Expected behavior**
I would expect that a help message in English (or another translatable to English Langauge string) appeared on the screen and in the text log.

**Screenshots**
N/A

**Additional context**
I am a professional games/video games developer and I use Poketwo primarily to help provide reminders/distractions/entertainment to other not-for-profits in the United States, Canada, Japan, France, the UK, and Austria. English is not my best langauge, but I can provide a suitable error string suggestion upon request.

**Comment by WitherredAway** [comment]
Hey, thank you for the report. Could you provide screenshots of these DMs with pokétwo? Would help us understand the problem more

**Comment by jculpon** [comment]
> Hey, thank you for the report. Could you provide screenshots of these DMs with pokétwo? Would help us understand the problem more

No, I clear my DMs when I switch accounts, you can do the following to reproduce this issue before I patch it myself:
1. Read the entire BUG again.
2. Open a PIRVATE/DIRECT MESSAGE with POKETWO using your DISCORD CLIENT.
3. SEND POKETWO a PIRVATE/DIRECT MESSAGE with YOUR DISCORD CLIENT.
4. SEND STRING `p!catch`
5. READ/VIEW REPLY
6. SEND STRING `p!help catch`
8. SEND STRING `p!help`
9. REREAD LOG, ATTACH SCREENSHOT

I am deaf/hoh and am currently working on a project in 日本語やフランス語や英語。Please contact '@peri' on the POKETWO DISCORD SERVER if you want to ping me about this ticket. Thank you/sorry, today is not a HOLIDAY/DAY OFF FOR ME.

**Comment by WitherredAway** [comment]
Thanks 👍 This will likely be addressed with our upcoming rewrite!

**Comment by jculpon** [comment]
> Thanks 👍 This will likely be addressed with our upcoming rewrite!

OK! Just let me know if you want me to submit a patch, I'm happy to help but haven't re-reviewed CONTRIBUTORS/CONTRIBUTING/NOT README.md since last night 🥂 /:the vert:/:tea: 8)

**Comment by jculpon** [comment]
Having reviewed them: I have no ethical concern with your choice of Contribution/Code of Conduct, but as I speak Japanese and work contract work: I am not currently employed by Nintendo of America or Nintendo of Japan directly. (if you need me to, I can close this, but am just getting notifs for this+contribs but  need to be offline for a few weeks to github due to USENIX PEPR 2022 and Cloudflare issues)

**Comment by WitherredAway** [comment]
I'll close it for you, thanks again for the report

**Comment by jculpon** [comment]
np/thanks, would look into fixing it myself if had the time this month o/~ happy capturing!
