### ISSUE TITLE
Pokemon Evolve Bug

### ISSUE THREAD

**Issue by The-flaSK** [poketwo/poketwo#447]
**Describe the bug**
When we run (p!evolve 91 91 91 91) it evolve only the pokemon 91 but it counts 4 times as we used 91 four times.
People Used This Bug To Complete The Recent Anniversary Event Quests.

**To Reproduce**
Do p!evolve <repeat same number many times>

**Expected behavior**
It will send --<pokemon> has evolved-- many times as we repeat pokemon id.

**Screenshots**
![Screenshot(6)](https://user-images.githubusercontent.com/86143326/175273445-4b1a3a49-d39c-4ffe-9f6e-58587d9fc088.png)

**Additional context**

**Comment by WitherredAway** [comment]
This has been fixed, thank you!
