### ISSUE TITLE
Trade Issues

### ISSUE THREAD

**Issue by jvsanchez17** [poketwo/poketwo#453]
**Describe the bug**
Sending the trade command results in the initial response, but interacting with the checkmark reaction doesn't initiate the trade. 

**To Reproduce**
- send trade command,
- interact with the check reaction,
- No trade initiates. 

**Expected behavior**
Trade initation.

**Additional context**
This is occurring in one of my servers, but not the other. The server id where poketwo is malfunctioning is 673603562856644608.
Permissions and settings are the same in both places.

**Comment by WitherredAway** [comment]
Trading works fine for me, could you please open a ticket on [our support server](https://discord.gg/poketwo-support) and ping me 267550284979503104 so that we can discuss this in more detail?
