### ISSUE TITLE
Incorrect picture displayed for Carracosta

### ISSUE THREAD

**Issue by hupmake** [poketwo/poketwo#458]
**Describe the bug**
As the title indicates, the image displayed for Carracosta is incorrect. 

**To Reproduce**
Have Carracosta spawn?

**Expected behavior**
An image of Carracosta appears. 

**Screenshots**
![50A2C501-87E0-46FD-BCB7-E4821150AB68](https://user-images.githubusercontent.com/53275084/179877265-9ea28cb3-b37d-4610-94e3-ed3bd0990a8e.jpeg)

**Comment by SuperJedi224** [comment]
There's an occasional bug where a new pokemon spawns but discord doesn't show the spawn message, so it's possible that a carracosta spawned after the genesect but the message either wasn't sent properly or isn't showing up on your client
