### ISSUE TITLE
Cannot switch back to starter

### ISSUE THREAD

**Issue by cefifer** [poketwo/poketwo#460]
Switched my starter Pokémon (rowlet #722) out for a different Pokémon and now cannot switch it back. Pokédex doesn’t have the starter listed.

**Steps To Reproduce**
I did p!select with appropriate dex number and it said cannot find, I did p!Pokédex and manually scrolled through everything and rowlet is not in the Pokédex.

**Expected behavior**
I expected my starter to be registered in my Pokédex and also accessible even if I switched it out for a different Pokémon.

**Comment by SuperJedi224** [comment]
Select commands use the local id number in your inventory, not the pokedex number

If you still have your starter, it will _probably_ be number 1, but you can do `p!p --n rowlet` to confirm

**Comment by cefifer** [comment]
Thanks so much for the quick response and solution that worked perfectly!
