### ISSUE TITLE
VERY delayed response from bot commands

### ISSUE THREAD

**Issue by CuteHeartCaty** [poketwo/poketwo#462]
**Describe the bug**
When a user types a command, the bot doesn't respond until up to 4 hours later
Side note: Pokémon also no longer seem to spawn

**To Reproduce**
Fix the delay

**Expected behavior**
The bot to respond instantly to a command

**Screenshots**
![image](https://user-images.githubusercontent.com/74067762/185821812-99c26d34-9694-4c32-a26f-13e5885f1294.png)
![image](https://user-images.githubusercontent.com/74067762/185821840-6fe8846a-4953-412d-84ea-37271f65acdf.png)

**Comment by Lovel-y** [comment]
Bruh, just read:

https://discord.com/channels/716390832034414685/717972767252676629/1011031752275415150

**Comment by CuteHeartCaty** [comment]
I'm not in the server but thanks, didn't need to be rude about it tho 😐

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
