### ISSUE TITLE
Delayed or non responsive 

### ISSUE THREAD

**Issue by SkeletonSlayer** [poketwo/poketwo#463]
For some reason when I type @poketwo etc it will either not respond or an hour later respond. Also I am unable to open my daily boxes I have voted and then I do @poketwo o u and it says you have no boxes. Then when I go to check my boxes it says I have non of any variety.

**Comment by Olifant1990** [comment]
You really opened a new issue without checking existing issues...???

https://github.com/poketwo/poketwo/issues/462

**Comment by SkeletonSlayer** [comment]
I looked at it but they posted images that made others not understand what
they meant read the responses to their issues and you’ll see why I made a
new one.
