### ISSUE TITLE
Shop issue

### ISSUE THREAD

**Issue by JudasStxr** [poketwo/poketwo#466]
Issue with shop command

When you run @Poketwo shop it works just fine but if you do @poketwo shop page 1 it won't work as I tried to open page 6 today

Is this possibly because of the command switch? ive noticed alot of other commands don't work either like market.

**Comment by SuperJedi224** [comment]
Try `@Poketwo shop 1`

**Comment by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaoaaaaa** [comment]
ty that worked
