### ISSUE TITLE
Commands not working 

### ISSUE THREAD

**Issue by MysteriousDryad** [poketwo/poketwo#467]
Spawns work in my server but none of the commands work. Everything has been tried to get it to work to no success. Only has been having issues since the bot went down couple days ago. I know other servers have been having this issue as well.

**Comment by TanNguyenChannel1** [comment]
Did you try to mention bot?

**Comment by MysteriousDryad** [comment]
Yes. Nothing worked.

**Comment by MysteriousDryad** [comment]
The fixes Oliver did seemed to fix the issue. Thanks yall!
