### ISSUE TITLE
Prefix not working 

### ISSUE THREAD

**Issue by pnymmas** [poketwo/poketwo#468]
Our prefix was changed right before that bot went down the other day. But it was changed to < 

So now when you use < it prompts you to mention the bot.. but mentioning the bot does nothing. 

![Screenshot_2022-08-31-12-18-47-17_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/112534850/187592471-4247d410-be20-4be0-b4af-8eb6df7b230c.jpg)

**Comment by TomEpsilon** [comment]
Try kicking the bot and reinviting it.

**Comment by pnymmas** [comment]
We have, it doesn't reset any of the settings.

**Comment by pnymmas** [comment]
The update fixed it, thank you!
