### ISSUE TITLE
able to see other people's profile

### ISSUE THREAD

**Issue by Naman23-coder** [poketwo/poketwo#469]
**Is your feature request related to a problem? Please describe.**
able to see other people's profile

**Describe the solution you'd like**
I think we can do something like
```
@Poketwo profile <mention>
```
we can make changes in code like
```py
async def profile(ctx , * , _member = Optional[discord.Member])
    if _member is None:
            member = ctx.author
    else:
           member = _member 
```

**Additional context**
I am happy to contribute to this (if you approve this)

**Comment by Mintmoon33** [comment]
I don't think they will add that since privacy issue

**Comment by VarMonke** [comment]
This is a major privacy concern and I'm not sure if we're going to add it any time soon.
(PS: The code isn't correct. `_member: Optional[discord.Member] = None`)

**Comment by Naman23-coder** [comment]
@VarMonke anyways thanks
