### ISSUE TITLE
the learning new moves for pokemon is not working

### ISSUE THREAD

**Issue by PsychicSlash** [poketwo/poketwo#472]
whenever anyone tries to learn new pokemon moves ,the bot says aborted no matter how much u try

![image](https://user-images.githubusercontent.com/112756196/188266233-91db717b-4be2-4c03-bf1d-817d3197dae6.png)

**Comment by VarMonke** [comment]
Hello! We're aware of this issue and are working on a fix right now.
[This is due to the recent changes on discord's end ](https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-FAQ)
Sorry for the inconvenience.
