### ISSUE TITLE
Unable to learn new / replace moves.

### ISSUE THREAD

**Issue by PipC0** [poketwo/poketwo#473]
**Describe the bug**
Trying to learn a new move while having the max amount of moves leads to Aborted message when choosing a move to replace with.
**To Reproduce**
Steps to reproduce the behavior.
You would type the command the command as well as the new move you are trying to learn. (@poketwo learn (move))
And the bot will ask to choose a move to replace the new move with. 
and once typing the move I want to replace with. The bot will respond with Aborted.
**Expected behavior**
To replace the old move with the new move I intend on learning.

**Screenshots**
![Screenshot 2022-09-05 004532](https://user-images.githubusercontent.com/112832591/188338184-2b800454-c218-4585-8d9a-5fe7f002ddd7.png)

**Comment by dark-fedora** [comment]
Workaround: You may teach a pokemon new moves in a DM with Poketwo without issues.

This is likely due to the new limitation on prefixes for Poketwo due to privileged message content intents.
