### ISSUE TITLE
The learn command dosent give any output 

### ISSUE THREAD

**Issue by Ajknight1** [poketwo/poketwo#475]
the bot reads the message and dosent give any reply since it works like that (i mean it is supposed to read message and then process it and give an output and save it) now the output is being blocked due to some reason , and that's the problem the bot reads the message so i guess it's storing the message in the database (cause i tried to trade the poke with my friend even he can't change the move) so that's that , and yea it's serious cause one day or the other everyone will get affected by it.

The issue is noticed by some helpers 

![Screenshot_2022-09-09-17-44-15-00](https://user-images.githubusercontent.com/113235506/189477944-b007ffbe-fcf2-4423-9767-4349ca3db14d.jpg)

**Comment by WitherredAway** [comment]
I'm fairly certain this was fixed earlier today in ae9c9fa03841af38db986b46b0e6932dfd3d1bf7

Could you check once again if you are still facing this issue?

**Comment by JensKoekkoek** [comment]
> I'm fairly certain this was fixed earlier today in [ae9c9fa](https://github.com/poketwo/poketwo/commit/ae9c9fa03841af38db986b46b0e6932dfd3d1bf7)
> 
> Could you check once again if you are still facing this issue?

I believe this fixed new instances of this issue occurring, but Pokémon that had previously learned a move twice due to the issue are still unable to learn any moves even now.

**Comment by WitherredAway** [comment]
I see, I'll let the developer know. Thanks
