### ISSUE TITLE
Server Members are Unable to Receive Voting Rewards

### ISSUE THREAD

**Issue by KahiliMoo** [poketwo/poketwo#480]
After the bot went down temporarily, it gave my server members the ping to vote. They voted, used the daily command, and the bot did not register the vote. But top.gg counted it as already voted, not giving them their reward. 

I have told them to sign out of top.gg then re-sign it. This still did not fix it. 

**Expected behavior**
We expected that after voting we would receive our pokebox per usual but came across this bug instead. 
![DDB23438-6F4F-49E9-A19C-C6413ABF10E0](https://user-images.githubusercontent.com/114013848/191316743-8ac9a723-344a-4279-be1f-79f38f17e87e.png)
![72E10677-BDF6-47D3-BE00-1F647824443D](https://user-images.githubusercontent.com/114013848/191316758-6a4eeb3d-2fde-432a-80cb-378d22bb2596.png)

**Comment by oliver-ni** [comment]
The bot was unable to process new votes for a few hours after it came back up — the timer will normalize after 12 hours
