### ISSUE TITLE
I can't buy / use incense

### ISSUE THREAD

**Issue by m4cedo** [poketwo/poketwo#481]
![Screenshot_2022-09-20-15-46-29-774_com discord](https://user-images.githubusercontent.com/76791782/191339587-22b823cc-a34a-4890-a32e-f000edbaa8de.jpg)

I've been trying to use incense on my server since the moment it was reopened, but since then this message pops up when I go to buy.
Note: This message may contain errors because I am Brazilian.

**Comment by oliver-ni** [comment]
Forgot to re-enable it after yesterday's downtime. Should be good now. Thanks!

**Comment by Jasmine10002** [comment]
> Forgot to re-enable it after yesterday's downtime. Should be good now. Thanks!

it still doesnt work
