### ISSUE TITLE
incense not on after stated it was

### ISSUE THREAD

**Issue by Jasmine10002** [poketwo/poketwo#484]
I can not buy private incenses, even after it has been said to have been fixed.

to reproduce, just try to purchase a incense in your own private server

i expected my incense to start but this was not the case

![image](https://user-images.githubusercontent.com/104651980/191351660-a69c43c0-d20e-4970-b7dd-c8fbce49c129.png)
![image](https://user-images.githubusercontent.com/104651980/191351799-559cbae1-a7d1-4fb3-a154-09e9cd0bf1a8.png)

this is very frustrating and i just want incenses back

**Comment by Jasmine10002** [comment]
@oliver-ni am i doing something wrong or does the bot need to be refreshed or something?

**Comment by WitherredAway** [comment]
Extremely sorry about the delayed response! Please open a ticket on [our support server](https://discord.gg/poketwo-support) if you still need support with this!
