### ISSUE TITLE
I cant upvote

### ISSUE THREAD

**Issue by SoulFolker** [poketwo/poketwo#489]
I cant vote at top.gg. Somehow it appear as Error Code 1020.

Im not sure if this the right place to reach out but I can't figure out how and where to contact.

![image](https://user-images.githubusercontent.com/115682813/195500617-eca25604-10c2-4fb2-ae19-6e9594f0330c.png)

**Comment by oliver-ni** [comment]
Hi, looks like it's a Top.gg issue. Please ask Top.gg at [their Discord server](https://discord.gg/dbl).
