### ISSUE TITLE
@poketwo shop page=1 is not working! it keeps saying "Converting to "int" failed for parameter "page"."

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaoaaaaa** [poketwo/poketwo#490]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by WitherredAway** [comment]
I'll close this issue since it seems like you have found the solution 😎
