### ISSUE TITLE
Duplicate Pokemon Listing 

### ISSUE THREAD

**Issue by NEUDitao** [poketwo/poketwo#491]
During a listing/battle of Pokemon, there was a duplicate listing for Pokemon ID 8: between Weedle and Litten. However, Litten was unchoosable through the API.

![Screen Shot 2022-11-03 at 11 39 04 AM](https://user-images.githubusercontent.com/33675688/199766263-0a12b059-a0c1-4807-9a8b-13c682264e05.png)

**Comment by oliver-ni** [comment]
Hi, canyou please run `@Pokétwo reindex`?

That should fix the numbering issues.
