### ISSUE TITLE
AND operator 

### ISSUE THREAD

**Issue by cBbagel** [poketwo/poketwo#492]
I would like to be able to submit multiple commands on one line.

Right now to select a pokemon and nickname it I have to put these commands one after the other like so:

1 @poketwo select 2
2 @poketwo nick [name]

I would like to be able to invoke the commands like so

1 @poketwo select 2 && nick [name]

OR

1 @poketwo select 2 && @poketwo nick [name]

This is just 2 commands though and maybe don't need to be on one line but if this was learning new moves it would be nice to be able to learn multiple moves at one time instead of on separate entries.

**Comment by WitherredAway** [comment]
Thanks for the suggestion. However, as there is already an issue similar to this (#421), I'll be closing this ticket as a duplicate.
