### ISSUE TITLE
Galar e Hisuian 

### ISSUE THREAD

**Issue by MeItadori** [poketwo/poketwo#495]
**Where are Galar's moves?** Galar and Hisuian 

Please add Galar and Hisuian moves. Pokemons like scorbunny, enamorus and Hisuian Zoroark, are useless in the bot without moves. That's why I ask for moves from Galar and Hisuian.

~MeItadoriღ

**Comment by bmochan** [comment]
A video demonstration of how the autocatcher works: https://www.youtube.com/watch?v=9-z77IQKulQ&t=13s

**Comment by bmochan** [comment]
A video demonstration of how the autocatcher works: https://www.youtube.com/watch?v=9-z77IQKulQ&t=13s

**Comment by bmochan** [comment]
@everyone A video demonstration of how the autocatcher works: https://www.youtube.com/watch?v=9-z77IQKulQ&t=13s

**Comment by bmochan** [comment]
@Oliver#0001 A video demonstration of how the autocatcher works: https://www.youtube.com/watch?v=9-z77IQKulQ&t=13s

**Comment by bmochan** [comment]
<@398686833153933313> fix the autocatcher ong

**Comment by bmochan** [comment]
<@880138296250998834>

**Comment by bmochan** [comment]
A video demonstration of how the autocatcher works: https://www.youtube.com/watch?v=9-z77IQKulQ&t=13s @here @everyone @Trading

**Comment by bmochan** [comment]
A video demonstration of how the autocatcher works: https://www.youtube.com/watch?v=9-z77IQKulQ&t=13s <@785677438251696139>

**Comment by Anoeaa** [comment]
The moves is on the to-do list. This will be worked on after the Rewrite of the whole bot.
