### ISSUE TITLE
Show all pokemons you have in the pokedex

### ISSUE THREAD

**Issue by FamousWolluf** [poketwo/poketwo#496]
**Is your feature request related to a problem? Please describe.**
No it's not realated to any problems

**Describe the solution you'd like**
I think it would be amazing, and I hear this from many people in my community, that we can see which pokemons we have. Like a thicked off pokedex style. 
Right now if you get the pokedex info on evolved pokemons or dialy rewarded pokemon they dont show up as owned in ur pokedex. This is because atm its only showing catched stats.
In the real pokemon games you will see all pokemons in the pokedex you have including the ones you evolved.

**Additional context**
Not that I know off.

**Comment by Anoeaa** [comment]
The Pokédex only registers the Pokémon you have caught. This is to make finishing the Pokédex more of a challenge. Evolved and boxed Pokémon don't count with this.

Because of the intended way it works now, I will close this issue. Thanks for your suggestion!
