### ISSUE TITLE
I bid on auction after that auction ended another player won the auction and i didn't get my pc back auction id - 913977 please check and solve this  

### ISSUE THREAD

**Issue by Heloteam12** [poketwo/poketwo#518]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by WitherredAway** [comment]
Hey there, really sorry about the delayed response. Do you still need support for this? If so, please open a ticket in [our support server](https://discord.gg/poketwo-support).
