### ISSUE TITLE
Voting isn't working

### ISSUE THREAD

**Issue by CatsFourLife** [poketwo/poketwo#519]
**Describe the bug**
Me and other person were trying to vote yesterday and it wasn't taking our votes. I tryed ageing today and same thing wasn't taking votes.

**Comment by Vigentian** [comment]
Issues with voting on Top.gg or Discord Bot List should not be reported as issues with the Pokétwo bot. If you are experiencing such issues, you can try things like making sure you're voting with the correct account, using a different device, or using a different browser.
