### ISSUE TITLE
Can't see the content of the Poketwo bot's messages

### ISSUE THREAD

**Issue by SageGreenSheep** [poketwo/poketwo#524]
So when im on the phone or discord i do see that Poketwo is popping up with messages but it is not showing anything while other people can clearly see what it says. As you will see in the  picture itself it does show the text itself but not the pictures weirdly enough.
![Screenshot_20230701_153910_Discord](https://github.com/poketwo/poketwo/assets/139187041/678d3c6a-812e-4544-b1d8-2a996794ee99)

**Comment by WitherredAway** [comment]
This occurs due to a discord setting on your end. Go to `Settings > Text & Media` and turn on this setting: 
![Screenshot_2023-07-11-11-03-10-107](https://github.com/poketwo/poketwo/assets/81734495/bc4d7420-0284-4334-9e3d-66f3e3109910)
