### ISSUE TITLE
Suspension 

### ISSUE THREAD

**Issue by Yuv120** [poketwo/poketwo#538]
A person is adding our user id in autocatchers and you guys banning Innocent people pls check that

**Comment by chrisp1v** [comment]
Autocatchers can't function only based on the userid. They require an unique token (also called discord token) in order to be able to talk to discords API. So yeah there's nothing to be checked.

**Comment by Yuv120** [comment]
Bro I didn't do anything please.

**Comment by WitherredAway** [comment]
You can appeal for your suspension at https://forms.poketwo.net/a/suspension-appeal, this place is not meant for that. Please wait for a response if you've already done so and have not received one yet.

**Comment by Yuv120** [comment]
Please give me one chance pls pls bruh ....a humble request
