### ISSUE TITLE
Command p --galarian --hisuian --alolan not working properly

### ISSUE THREAD

**Issue by AmartyaSingh97** [poketwo/poketwo#541]
**Describe the bug**
When we use command like p --ub --leg --myth , it basically shows all of these pokes. I tried something similar with p --galarian --hisuian --alolan, but it's not working.

**To Reproduce**
do p --galarian --hisuian --alolan and then do them separately like p --galarian , etc.

**Expected behavior**
Should show all alolan, hisuian and galarian pokes at once.

**Screenshots**
 
![Screenshot 2023-09-07 165811](https://github.com/poketwo/poketwo/assets/85061899/e5a2b0af-ceab-499c-8f21-07019443046a)

![Screenshot 2023-09-07 165821](https://github.com/poketwo/poketwo/assets/85061899/86826f7b-565a-4200-a92e-7da46bcce9ab)

**Additional context**

**Comment by WitherredAway** [comment]
Thanks for the issue. I will implement this.

**Comment by AmartyaSingh97** [comment]
I forgot to mention the market command, this needs to be implemented in the market search command too.
Thank you.

**Comment by WitherredAway** [comment]
This has been implemented, thank you for the suggestion! (#551)
