### ISSUE TITLE
New user. Help?! 

### ISSUE THREAD

**Issue by DuckyHooligan** [poketwo/poketwo#543]
Im trying to pick a starter pokemon but it tells me to read and accept the terms and services. So i did. I have probably read the terms of services page like 10 times and i cannot find the accept button. 

Ive asked the server general chat for help but nobody replied... 

![Screenshot_20230909_234444_com discord](https://github.com/poketwo/poketwo/assets/144398293/49607a29-aa17-4fec-8283-1c9f226d5b90)

**Comment by WitherredAway** [comment]
Please try updating your discord, the button shows fine for me!
