### ISSUE TITLE
What features are paid?

### ISSUE THREAD

**Issue by HoutarouOreki** [poketwo/poketwo#573]
I reviewed the ToS and there seems to be a store and indeed there is:
![img](https://github.com/poketwo/poketwo/assets/16261733/a56cc1c5-9460-46a4-afe3-23e19763ba73)

I don't want to start using this service if my friends are gonna get roadblocked with paid features. But I can't find any info on what features "Shards" are actually used for now and in the future, it just says that it can change at any moment.

For sure I'd support after I found the app to be fun, but I don't want to add it for my server if my friends are gonna get ads or missing features and have to pay after they're already engaged into the app.

**Comment by WitherredAway** [comment]
Hey there! Those are very valid concerns. There are no advertisements in Pokétwo. And every feature is available to everyone, there is no paywall. **Even this item that you see on the website, "Shards", is available to purchase for free using Pokécoins (main in-game currency that is widely obtainable through playing the bot) by anyone.**

"Shard" is a currency in the bot that allows you to purchase special items such as Incenses (automatic pokemon spawns), Redeems (spawn any pokemon), Shiny Charms (+20% chance of shiny) and potentially more in the future.

The store is mainly for users who want to support the bot and/or get some more Shards instantly, and is totally optional.

**Comment by HoutarouOreki** [comment]
Ok, thank you!
