### ISSUE TITLE
Request: Mass release commands

### ISSUE THREAD

**Issue by Trinity343** [poketwo/poketwo#580]
I would love to have the ability to have some mass-release commands

!p release [args...]

--name
--Iv (<,>,=)
--level (<,>,=)
--shiny (True, False) | ability to choose if Shiny pokemon are included in being released or not
--nick (True, False) | ability to choose if those with nicknames are included in being released or not

This would make pokemon catch management way easier and cleaner.

**Comment by WitherredAway** [comment]
Hey there, thank you for the suggestion but this is already a thing! The command is `@Pokétwo releaseall` and supports [all the flags you mentioned and much more](https://docs.poketwo.net/intermediate-topics/search-filters#id-7.-releaseall-poketwo-8236-ra)!

The only thing that you mentioned that is not supported is the ability to specify `False` for flags such as `--shiny`. But an exclusion system is planned to be added in the future.

**Comment by Trinity343** [comment]
ah Good to know.  I had no idea those commands existed since. I never thought to use the help command specifically for the releaseall. i assumed it was limited to the name it says it is.. and would release all and had no arguments with it

Thank you
