### ISSUE TITLE
wiki - user howto guide

### ISSUE THREAD

**Issue by activedecay** [poketwo/poketwo#581]
# A clear and concise description of what the problem is.
users of the bot don't have any clue how to use it (me included).

# Describe the solution you'd like
a wiki page or README.md of basic commands, a step by step guide, getting started, basic feature descriptions for users in the discord.

**Additional context**
like for real

**Comment by WitherredAway** [comment]
Hey! We do have documentation: https://docs.poketwo.net. This has a lot of guides, tips and tricks and information on almost all commands and flags. This is pretty up to date, but there are some things missing that may take time to get updated. It is still considered a work-in-progress though, hence hasn't been mentioned more.

You can also see a list of commands directly in the bot using `@‌Pokétwo#8236 help`

**Comment by WitherredAway** [comment]
You can also join our official server at https://discord.gg/poketwo for support
