### ISSUE TITLE
Evolved pokemon don't count towards pokedex

### ISSUE THREAD

**Issue by benduckwdesign** [poketwo/poketwo#582]
**Describe the bug**
Catch an evolvable pokemon. Evolve it. Only the base pokemon is shown as caught in your pokedex.

**Expected behavior**
The evolutions should be registered in the pokedex.

**Screenshots**
![problem](https://github.com/poketwo/poketwo/assets/5730541/5046e54d-c8f5-46bb-b443-678d2d2b4352)

**Comment by benduckwdesign** [comment]
This is a separate mention from the fact the gift pokemon also aren't added, would add another bug report for that one but didn't want to clog the issue tracker. They should be easy enough to fix at the same time.

**Comment by WitherredAway** [comment]
This is intended behaviour. Since market purchases, evolutions, trades, etc are very easy to do, they are not counted as pokedex entries, only caught pokemon are.
