### ISSUE TITLE
Turn April Fool's feature off

### ISSUE THREAD

**Issue by Greglar4** [poketwo/poketwo#583]
It is no longer April Fool's day but the spawned Pokemon are still the April Fool's images.

**Comment by kyan0045** [comment]
As specified [here](https://discord.com/channels/716390832034414685/717883936314753045/1224308840829419530) they would stay like this for a week, which starting from April 1st would mean that the regular images will return today..

Edit: They're back already

**Comment by Greglar4** [comment]
Ah I see, I'll close this then.
