### ISSUE TITLE
Redirecting Level Up Embeds

### ISSUE THREAD

**Issue by bonkmilk** [poketwo/poketwo#584]
**Is your feature request related to a problem? Please describe.**
I saw a post while looking for this feature requesting this feature, that got dismissed and closed because "silence exists" and the use case was too narrow. I disagree, almost everyone in my personal friend group and servers I've talked about this with are annoyed by the embeds popping up in any channel, it's just as annoying as pokemon spawns, and it is also something that I don't want to MISS either, as I and several of my friends like to aim to get pokemon to specific levels for aesthetic collection purposes, so silencing is too severe of a "fix" to the embeds popping up.

**Describe the solution you'd like**
The ability to redirect Pokemon Level Up embeds to a different channel, exactly like you can with pokemon spawns. Ideally, they could be two separate channels, so that it is possible to have a pokemon category with a streamlined, organized channel for spawns and for levels. I already have my botsd broken down into channels for specific use-cases, so having the option for more organization of bot posting and bot commands would be amazing.

**Additional context**
I honestly don't know why someone dismissed this request before and closed the ticket. Was it too hard for them to figure out how to make it happen? (Not like I would know the first thing about coding osmething like that, of course, but I'll freely admit that)

**Comment by WitherredAway** [comment]
The previous issue on this, #532, is still open and in consideration. As such I am going to close this as duplicate.

**Comment by aarenmarchi** [comment]
oop
