### ISSUE TITLE
so i found this autocatcher called pokefier on yt idk if it s illegal or not?

### ISSUE THREAD

**Issue by PumpkinDaBlaze** [poketwo/poketwo#585]
https://www.youtube.com/watch?v=0qbvIiR5PzE

**Comment by WitherredAway** [comment]
It is against poketwo TOS and will get your poketwo account permanently suspended

**Comment by PumpkinDaBlaze** [comment]
ty

**Comment by Karewen** [comment]
how can i get permanently banned if i use it in a brand new alt and in a private server with no affiliations to my main account? if no one reports me there is no way to get banned

**Comment by WitherredAway** [comment]
We have ways of detection
