### ISSUE TITLE
Allow certain messages only to the specific user

### ISSUE THREAD

**Issue by ConnerWithAnE** [poketwo/poketwo#587]
**Is your feature request related to a problem? Please describe.**
My problem is that when other users want to use the shop or see their Pokemon it goes out to the whole chat and can get spammy.

**Describe the solution you'd like**
Set an option for certain notifications like a level up, checking Pokemon, or checking the shop to send as messages only seen by the user who initiated them. Perhaps an option to allow for certain level milestones to be displayed only. 

**Additional context**
I can work on adding the feature I just want to make sure it does not already exist.

**Comment by WitherredAway** [comment]
Ephemeral messages (the "only you can see this message" messages) are only possible via slash commands or UI components such as buttons and select menus. We might do this when we implement slash commands, but at the moment it is not possible.
