### ISSUE TITLE
Counters of each pokemon don't move up after trading for my pokemon list

### ISSUE THREAD

**Issue by Monica-Lu** [poketwo/poketwo#588]
**Describe the bug**
After trading the 7th pokemon in my pokemon list with another user using(Use trade command add 7), the counters don't move up and have 6th skipping over 7th to 8th. 

**To Reproduce**
User: Use trade command @username 
Poketwo: Requesting a trade with @username. Click the accept button to accept!
User: Use trade command add *a number in the list*, and then confirm trading from both users
and then Use pokemon command(show the list of pokemon a user has)

**Expected behavior**
The counters should not skip any number while showing the list of pokemons a user have in order.

**Screenshots**
<img width="336" alt="Screenshot 2024-07-18 at 9 09 45 PM" src="https://github.com/user-attachments/assets/617b6dab-64d8-4c91-929d-56ceead12650">

**Additional context**

**Comment by Vigentian** [comment]
The bot already has a command you can use to correct the indices in your Pokémon list: `@Pokétwo#8236 reindex`.

**Comment by thaidzdzdz** [comment]
give me 1b pc now!!!!!!!!!!!!!!!!!!!!!!!!!!!!
