### ISSUE TITLE
How to consume tickets if team was not choosen before event ended.

### ISSUE THREAD

**Issue by Kayade00** [poketwo/poketwo#589]
Hi i saved up a bunch of tickets but forgot to join a team. Now, when I try to use them, I get a message saying 'Please join a team,' but the event has already ended. Will these tickets be automatically converted, or are they no longer usable?

**Comment by WitherredAway** [comment]
Unfortunately you can no longer join a team, and hence cannot use your tickets. Tickets will be converted to pokecoins later.

**Comment by Kayade00** [comment]
> Unfortunately you can no longer join a team, and hence cannot use your tickets. Tickets will be converted to pokecoins later.
Hi there, as mentioned earlier, are tickets automatically converted, or were they affected by the bot's downtime? Will they be converted later when the bot is completely stable?

**Comment by WitherredAway** [comment]
> > Unfortunately you can no longer join a team, and hence cannot use your tickets. Tickets will be converted to pokecoins later.
> > Hi there, as mentioned earlier, are tickets automatically converted, or were they affected by the bot's downtime? Will they be converted later when the bot is completely stable?

The event claiming period isn't over yet due to the outages, we'll  announce when that period ends + tickets are converted
