### ISSUE TITLE
Magical Leaf always misses.

### ISSUE THREAD

**Issue by TheNerdRealm** [poketwo/poketwo#60]
I recently did a battle and the player kept using Magical Leaf with his Bayleaf and the move always missed. But when you type in p!moveinfo magical leaf, it states that the move "Never Misses".

**Comment by UnoriginalDood** [comment]
same thing with feint attack

**Comment by 3favoritepower** [comment]
any move that igonore evasion and acuracty even aerial ace

**Comment by WitherredAway** [comment]
Known bug, it's most likely planned to be fixed with the battle update
