### ISSUE TITLE
New boost

### ISSUE THREAD

**Issue by Roli0109** [poketwo/poketwo#73]
boost which boosts spawning on the server

**Comment by DevilJamJar** [comment]
Could you be more specific? Would this act the same as a regular boost server-wide, meaning a Pokémon spawn in every channel every 20 seconds, or would that boost spawn a Pokémon every 20 seconds in a random channel?

Please add the enhancement label also.

**Comment by kyle-he** [comment]
I'm assuming this means that you want a higher chance of getting certain pokémon, so I will be closing this issue.
